/*
 * Original cards from The Witcher 3
 */

var default_cards = {
    "ntr_mysterious_elf": {
        "name": "Avallach'h",
        "id": 0,
        "deck": "neutral",
        "row": "close",
        "strength": "0",
        "ability": "hero spy",
        "filename": "mysterious_elf",
        "count": "1",
        "quote": "You humans have... unusual tastes."
    },
    "spe_decoy": {
        "name": "Decoy",
        "id": 1,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "decoy",
        "filename": "decoy",
        "count": "3",
        "quote": "When you run out of peasants, decoys also make decent arrow fodder."
    },
    "spe_frost": {
        "name": "Biting Frost",
        "id": 2,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "frost",
        "filename": "frost",
        "count": "3",
        "quote": "Best part about frost - bodies of the fallen don't rot so quickly."
    },
    "ntr_ciri": {
        "name": "Cirilla Fiona Elen Riannon",
        "id": 3,
        "deck": "neutral",
        "row": "close",
        "strength": "15",
        "ability": "hero",
        "filename": "ciri",
        "count": "1",
        "quote": "Know when fairy tales cease to be tales? When people start believing in them."
    },
    "spe_clear": {
        "name": "Clear Weather",
        "id": 4,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "clear",
        "filename": "clear",
        "count": "2",
        "quote": "The sun' shinin', Dromle! The sun's shinin'! Maybe there's hope left after all..."
    },
    "spe_horn": {
        "name": "Commander's Horn",
        "id": 5,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "horn",
        "filename": "horn",
        "count": "3",
        "quote": "Plus one to morale, minus three to hearing."
    },
    "ntr_dandelion": {
        "name": "Dandelion",
        "id": 6,
        "deck": "neutral",
        "row": "close",
        "strength": "2",
        "ability": "horn",
        "filename": "dandelion",
        "count": "1",
        "quote": "Dandelion, you're a cynic, a lecher, a whoremonger, a liar - and my best friend."
    },
    "ntr_emiel": {
        "name": "Emiel Regis Rohellec Terzieff",
        "id": 7,
        "deck": "neutral",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "emiel",
        "count": "1",
        "quote": "Men, the polites ones at least, would call me a monster. A blood-drinking freak."
    },
    "ntr_geralt": {
        "name": "Geralt of Rivia",
        "id": 8,
        "deck": "neutral",
        "row": "close",
        "strength": "15",
        "ability": "hero",
        "filename": "geralt",
        "count": "1",
        "quote": "If that's what it takes to save the world, it's better to let that world die."
    },
    "spe_fog": {
        "name": "Impenetrable Fog",
        "id": 9,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "fog",
        "filename": "fog",
        "count": "3",
        "quote": "A good commander's dream... a bad one's horror."
    },
    "spe_scorch": {
        "name": "Scorch",
        "id": 10,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "scorch",
        "filename": "scorch",
        "count": "3",
        "quote": "Pillars of flame turn the mightiest to ash. All others tremble in shock and awe."
    },
    "spe_rain": {
        "name": "Torrential Rain",
        "id": 11,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "rain",
        "filename": "rain",
        "count": "2",
        "quote": "Even the rain in this land smells like piss."
    },
    "ntr_triss": {
        "name": "Triss Merigold",
        "id": 12,
        "deck": "neutral",
        "row": "close",
        "strength": "7",
        "ability": "hero",
        "filename": "triss",
        "count": "1",
        "quote": "I can take care of myself. Trust me."
    },
    "ntr_vesemir": {
        "name": "Vesemir",
        "id": 13,
        "deck": "neutral",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "vesemir",
        "count": "1",
        "quote": "If you're to be hanged, ask for water. Anything can happen before they fetch it."
    },
    "ntr_villen": {
        "name": "Villentretenmerth",
        "id": 14,
        "deck": "neutral",
        "row": "close",
        "strength": "7",
        "ability": "scorch_c",
        "filename": "villen",
        "count": "1",
        "quote": "Also calls himself Borkh Three Jackdaws... he's not the best at names."
    },
    "ntr_yennefer": {
        "name": "Yennefer of Vengerberg",
        "id": 15,
        "deck": "neutral",
        "row": "ranged",
        "strength": "7",
        "ability": "hero medic",
        "filename": "yennefer",
        "count": "1",
        "quote": "Magic is Chaos, Art and Science. It is a curse, a blessing and a progression."
    },
    "ntr_zoltan": {
        "name": "Zoltan Chivay",
        "id": 16,
        "deck": "neutral",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "zoltan",
        "count": "1",
        "quote": "Life without old mates and booze is like a woman without a rump."
    },
    "ntr_olgierd": {
        "name": "Olgierd von Everec",
        "id": 17,
        "deck": "neutral",
        "row": "agile",
        "strength": "6",
        "ability": "morale",
        "filename": "olgierd",
        "count": "1",
        "quote": "At least you now know I don't easily lose my head."
    },
    "ntr_gaunter_odimm": {
        "name": "Gaunter O'Dimm",
        "id": 18,
        "deck": "neutral",
        "row": "siege",
        "strength": "2",
        "ability": "muster",
        "filename": "gaunter_odimm",
        "count": "1",
        "target": "ntr_gaunter_odimm",
        "quote": "He always grants exactly what you wish for. That's the problem."
    },
    "ntr_gaunter_odimm_darkness": {
        "name": "Gaunter O'Dimm - Darkness",
        "id": 19,
        "deck": "neutral",
        "row": "ranged",
        "strength": "4",
        "ability": "muster",
        "filename": "gaunter_odimm_darkness",
        "count": "3",
        "target": "ntr_gaunter_odimm",
        "quote": "Fear not the shadows, but the light."
    },
    "ntr_cow": {
        "name": "Cow",
        "id": 20,
        "deck": "neutral",
        "row": "ranged",
        "strength": "0",
        "ability": "avenger",
        "filename": "cow",
        "count": "1",
        "target": "ntr_chort",
        "quote": "Mooo!"
    },
    "ntr_chort": {
        "name": "Bovine Defense Force",
        "id": 21,
        "deck": "neutral",
        "row": "close",
        "strength": "8",
        "ability": "",
        "filename": "chort",
        "count": "0",
        "quote": "Grrrrr!"
    },
    "nr_foltest_king": {
        "name": "Foltest - King of Temeria",
        "id": 22,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_king",
        "filename": "foltest_king",
        "count": "1",
        "quote": "It is natural and beautiful that a man should love his sister."
    },
    "nr_foltest_lord": {
        "name": "Foltest - Lord Commander of the North",
        "id": 23,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_lord",
        "filename": "foltest_lord",
        "count": "1",
        "quote": "Sod advisors and their schemes. I place my trust in my soldiers' blades."
    },
    "nr_foltest_siegemaster": {
        "name": "Foltest - The Siegemaster",
        "id": 24,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_siegemaster",
        "filename": "foltest_siegemaster",
        "count": "1",
        "quote": "A well-aimed ballista razes not just the enemy's wall, but his morale as well."
    },
    "nr_foltest_steelforged": {
        "name": "Foltest - The Steel-Forged",
        "id": 25,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_steelforged",
        "filename": "foltest_steelforged",
        "count": "1",
        "quote": "A beautiful day for battle"
    },
    "nr_foltest_son_of_medell": {
        "name": "Foltest - Son of Medell",
        "id": 26,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_son",
        "filename": "foltest_son_of_medell",
        "count": "1",
        "quote": "Dammit, I rule this land and I refuse to creep around its corners."
    },
    "nr_ballista": {
        "name": "Ballista",
        "id": 27,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "ballista",
        "count": "1",
        "quote": "'Usually we give 'em female names.' 'Like Jenny?' 'More like Bertha.'"
    },
    "nr_blue_stripes_1": {
        "name": "Blue Stripes Commando",
        "id": 28,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_1",
        "count": "1",
        "target": "nr_blue_stripes",
        "quote": "I'd do anything for Temeria. Mostly, though, I kill for her."
    },
    "nr_blue_stripes_2": {
        "name": "Blue Stripes Commando",
        "id": 29,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_2",
        "count": "1",
        "target": "nr_blue_stripes",
        "quote": "I'd do anything for Temeria. Mostly, though, I kill for her."
    },
    "nr_blue_stripes_3": {
        "name": "Blue Stripes Commando",
        "id": 30,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_3",
        "count": "1",
        "target": "nr_blue_stripes",
        "quote": "I'd do anything for Temeria. Mostly, though, I kill for her."
    },
    "nr_catapult_1": {
        "name": "Catapult",
        "id": 31,
        "deck": "realms",
        "row": "siege",
        "strength": "8",
        "ability": "bond",
        "filename": "catapult_1",
        "count": "1",
        "target": "nr_catapult",
        "quote": "The gods help those who have better catapults."
    },
    "nr_catapult_2": {
        "name": "Catapult",
        "id": 32,
        "deck": "realms",
        "row": "siege",
        "strength": "8",
        "ability": "bond",
        "filename": "catapult_2",
        "count": "1",
        "target": "nr_catapult",
        "quote": "The gods help those who have better catapults."
    },
    "nr_crinfrid_1": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 33,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_1",
        "count": "1",
        "target": "nr_crinfrid",
        "quote": "Haven't had much luck with monsters of late, so we enlisted."
    },
    "nr_crinfrid_2": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 34,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_2",
        "count": "1",
        "target": "nr_crinfrid",
        "quote": "Haven't had much luck with monsters of late, so we enlisted."
    },
    "nr_crinfrid_3": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 35,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_3",
        "count": "1",
        "target": "nr_crinfrid",
        "quote": "Haven't had much luck with monsters of late, so we enlisted."
    },
    "nr_dethmold": {
        "name": "Dethmold",
        "id": 36,
        "deck": "realms",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "dethmold",
        "count": "1",
        "quote": "I conce made a prisoner vomit his own entrails... Ah, good times..."
    },
    "nr_banner_nurse": {
        "name": "Dun Banner Medic",
        "id": 37,
        "deck": "realms",
        "row": "siege",
        "strength": "5",
        "ability": "medic",
        "filename": "banner_nurse",
        "count": "1",
        "quote": "Stitch red to red, white to white, and everything will be all right."
    },
    "nr_esterad": {
        "name": "Esterad Thyssen",
        "id": 38,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "esterad",
        "count": "1",
        "quote": "Like all Thyssen men, he was tall, powerfully built and criminally handsome"
    },
    "nr_natalis": {
        "name": "John Natalis",
        "id": 39,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "natalis",
        "count": "1",
        "quote": "That square should bear the names of my soldiers, of the dead. Not mine."
    },
    "nr_kaedwen_siege": {
        "name": "Kaedweni Siege Expert",
        "id": 40,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege",
        "count": "1",
        "quote":"'You gotta recalibrate the arm by five degrees.' 'Do what by the what now?'"
    },
    "nr_kaedwen_siege_1": {
        "name": "Kaedweni Siege Expert",
        "id": 41,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege_1",
        "count": "1",
        "quote": "'You gotta recalibrate the arm by five degrees.' 'Do what by the what now?'"
    },
    "nr_kaedwen_siege_2": {
        "name": "Kaedweni Siege Expert",
        "id": 42,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege_2",
        "count": "1",
        "quote": "'You gotta recalibrate the arm by five degrees.' 'Do what by the what now?'"
    },
    "nr_keira": {
        "name": "Keira Metz",
        "id": 43,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "keira",
        "count": "1",
        "quote": "If I'm to die today, I wish to look smashing for the occasion."
    },
    "nr_philippa": {
        "name": "Philippa Eilhart",
        "id": 44,
        "deck": "realms",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "philippa",
        "count": "1",
        "quote": "Soon the power of kings will wither, and the Lodge shall seize its rightful place."
    },
    "nr_poor_infantry_1": {
        "name": "Poor Fucking Infantry",
        "id": 45,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_1",
        "count": "1",
        "target": "nr_poor_infantry",
        "quote": "I's a war veteran! ... spare me a crown?"
    },
    "nr_poor_infantry_2": {
        "name": "Poor Fucking Infantry",
        "id": 46,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_2",
        "count": "1",
        "target": "nr_poor_infantry",
        "quote": "I's a war veteran! ... spare me a crown?"
    },
    "nr_poor_infantry_3": {
        "name": "Poor Fucking Infantry",
        "id": 47,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_3",
        "count": "1",
        "target": "nr_poor_infantry",
        "quote": "I's a war veteran! ... spare me a crown?"
    },
    "nr_poor_infantry_4": {
        "name": "Poor Fucking Infantry",
        "id": 48,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_4",
        "count": "1",
        "target": "nr_poor_infantry",
        "quote": "I's a war veteran! ... spare me a crown?"
    },
    "nr_stennis": {
        "name": "Prince Stennis",
        "id": 49,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "spy",
        "filename": "stennis",
        "count": "1",
        "quote": "He ploughin' wears the golden armor. Golden. 'Course he's an arsehole."
    },
    "nr_redania": {
        "name": "Redanian Foot Soldier",
        "id": 50,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "",
        "filename": "redania",
        "count": "1",
        "quote": "I've bled for Redania! I've killed for Redania... Dammit, I've even raped for Redania!"
    },
    "nr_redania_1": {
        "name": "Redanian Foot Soldier",
        "id": 51,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "",
        "filename": "redania_1",
        "count": "1",
        "quote": "I've bled for Redania! I've killed for Redania... Dammit, I've even raped for Redania!"
    },
    "nr_sheldon": {
        "name": "Sheldon Skaggs",
        "id": 52,
        "deck": "realms",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "sheldon",
        "count": "1",
        "quote": "I was there, on the front lines! Right where the fightin' was the thickest!"
    },
    "nr_siege_tower": {
        "name": "Siege Tower",
        "id": 53,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "siege_tower",
        "count": "1",
        "quote": "I love the clamor of siege towers in the morning. Sounds like victory."
    },
    "nr_siegfried": {
        "name": "Siegfried of Denesle",
        "id": 54,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "siegfried",
        "count": "1",
        "quote": "We're on the same side, witcher. You'll realize this one day."
    },
    "nr_dijkstra": {
        "name": "Sigismund Dijkstra",
        "id": 55,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "spy",
        "filename": "dijkstra",
        "count": "1",
        "quote": "Gwent's like politics, just more honest."
    },
    "nr_sheala": {
        "name": "Síle de Tansarville",
        "id": 56,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "sheala",
        "count": "1",
        "quote": "The Lodge lacks humility. Our lust for power may yet be our undoing."
    },
    "nr_thaler": {
        "name": "Thaler",
        "id": 57,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "spy",
        "filename": "thaler",
        "count": "1",
        "quote": "Fuck off! We aren't all ploughin' philanderers. Some of us have depth..."
    },
    "nr_sabrina": {
        "name": "Sabrina Glevissig",
        "id": 58,
        "deck": "realms",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "sabrina",
        "count": "1",
        "quote": "The Daughter of the Kaedweni Wilderness."
    },
    "nr_vernon": {
        "name": "Vernon Roche",
        "id": 59,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "vernon",
        "count": "1",
        "quote": "A partiot... and a real son of a bitch."
    },
    "nr_ves": {
        "name": "Ves",
        "id": 60,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "ves",
        "count": "1",
        "quote": "Better to live one day as a king than a whole life as a beggar."
    },
    "nr_yarpen": {
        "name": "Yarpen Zigrin",
        "id": 61,
        "deck": "realms",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "yarpen",
        "count": "1",
        "quote": "The world belongs to whoever's best at crackin' skulls and impregnatin' lasses."
    },
    "nr_trebuchet": {
        "name": "Trebuchet",
        "id": 62,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "trebuchet",
        "count": "1",
        "quote": "Castle won't batter itself down, now will it? Get them trebuchets rollin'!"
    },
    "nr_trebuchet_1": {
        "name": "Trebuchet",
        "id": 63,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "trebuchet_1",
        "count": "1",
        "quote": "Castle won't batter itself down, now will it? Get them trebuchets rollin'!"
    },
    "ne_emhyr_imperial": {
        "name": "Emhyr var Emreis - His Imperial Majesty",
        "id": 64,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_imperial",
        "filename": "emhyr_imperial",
        "count": "1",
        "quote": "The skies wept when my Pavetta died. They will not weep for me."
    },
    "ne_emhyr_emperor": {
        "name": "Emhyr var Emreis - Emperor of Nilfgaard",
        "id": 65,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_emperor",
        "filename": "emhyr_emperor",
        "count": "1",
        "quote": "Your motives do not interest me. Only results."
    },
    "ne_emhyr_whiteflame": {
        "name": "Emhyr var Emreis - the White Flame",
        "id": 66,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_whiteflame",
        "filename": "emhyr_whiteflame",
        "count": "1",
        "quote" :"A sword is but one of many tools at a ruler's disposal."
    },
    "ne_emhyr_relentless": {
        "name": "Emhyr var Emreis - The Relentless",
        "id": 67,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_relentless",
        "filename": "emhyr_relentless",
        "count": "1",
        "quote": "They do not call me the Patient. Take care they do not call you the Headless."
    },
    "ne_emhyr_invader_of_the_north": {
        "name": "Emhyr var Emreis - Invader of the North",
        "id": 68,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_invader",
        "filename": "emhyr_invader_of_the_north",
        "count": "1",
        "quote": "Emperors command multitudes, yet cannot control two things: their time and their hearts."
    },
    "ne_albrich": {
        "name": "Albrich",
        "id": 69,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "albrich",
        "count": "1",
        "quote": "A fireball? Of course. Whatever Your Imperial Majesty whishes."
    },
    "ne_assire": {
        "name": "Assire var Anahid",
        "id": 70,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "assire",
        "count": "1",
        "quote": "Nilfgaardian mages do have a choice, servile submission, or the gallows."
    },
    "ne_black_archer": {
        "name": "Black Infantry Archer",
        "id": 71,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "",
        "filename": "black_archer",
        "count": "1",
        "quote": "I aim for the knee. Always."
    },
    "ne_black_archer_1": {
        "name": "Black Infantry Archer",
        "id": 72,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "",
        "filename": "black_archer_1",
        "count": "1",
        "quote": "I aim for the knee. Always."
    },
    "ne_cahir": {
        "name": "Cahir Mawr Dyffryn aep Ceallach",
        "id": 73,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "cahir",
        "count": "1",
        "quote": "His eyes flashed under his winged helmet. Fire gleamed from his sword's blade."
    },
    "ne_cynthia": {
        "name": "Cynthia",
        "id": 74,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "cynthia",
        "count": "1",
        "quote": "Cynthia's talents can be deadly. She needs a tight leash."
    },
    "ne_archer_support": {
        "name": "Etolian Auxiliary Archers",
        "id": 75,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "1",
        "ability": "medic",
        "filename": "archer_support",
        "count": "1",
        "quote": "Double or nothing, aim for his cock"
    },
    "ne_archer_support_1": {
        "name": "Etolian Auxiliary Archers",
        "id": 76,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "1",
        "ability": "medic",
        "filename": "archer_support_1",
        "count": "1",
        "quote": "Double or nothing, aim for his cock"
    },
    "ne_fringilla": {
        "name": "Fringilla Vigo",
        "id": 77,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "fringilla",
        "count": "1",
        "quote": "Magic is the highest good. It transcends all borders and divisions."
    },
    "ne_heavy_zerri": {
        "name": "Heavy Zerrikanian Fire Scorpion",
        "id": 78,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "10",
        "ability": "",
        "filename": "heavy_zerri",
        "count": "1",
        "quote": "Not the best for taking cities, but great for razing them to the ground."
    },
    "ne_imperal_brigade_1": {
        "name": "Impera Brigade Guard",
        "id": 79,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_1",
        "count": "1",
        "target": "ne_imperal_brigade",
        "quote": "The Impera Brigade never surrenders. Ever."
    },
    "ne_imperal_brigade_2": {
        "name": "Impera Brigade Guard",
        "id": 80,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_2",
        "count": "1",
        "target": "ne_imperal_brigade",
        "quote": "The Impera Brigade never surrenders. Ever."
    },
    "ne_imperal_brigade_3": {
        "name": "Impera Brigade Guard",
        "id": 81,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_3",
        "count": "1",
        "target": "ne_imperal_brigade",
        "quote": "The Impera Brigade never surrenders. Ever."
    },
    "ne_imperal_brigade_4": {
        "name": "Impera Brigade Guard",
        "id": 82,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_4",
        "count": "1",
        "target": "ne_imperal_brigade",
        "quote": "The Impera Brigade never surrenders. Ever."
    },
    "ne_letho": {
        "name": "Letho of Gulet",
        "id": 83,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "letho",
        "count": "1",
        "quote": "Witchers never die in the beds."
    },
    "ne_menno": {
        "name": "Menno Coehoorn",
        "id": 84,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "10",
        "ability": "hero medic",
        "filename": "menno",
        "count": "1",
        "quote": "I'll take an attentive reconnaissance unit over a fine cavalry brigade any day."
    },
    "ne_morteisen": {
        "name": "Morteisen",
        "id": 85,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "",
        "filename": "morteisen",
        "count": "1",
        "quote" :"No Nordling pikemen or dwarven spearbearers can hope to best trained cavalary."
    },
    "ne_moorvran": {
        "name": "Morvran Voorhis",
        "id": 86,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "10",
        "ability": "hero",
        "filename": "moorvran",
        "count": "1",
        "quote": "Summer sun reflecting in the quiet waters of Alba - that's Nilfgaard to me."
    },
    "ne_nauzicaa_1": {
        "name": "Nausicaa Cavalry Rider",
        "id": 87,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_1",
        "count": "1",
        "target": "ne_nauzicaa",
        "quote": "The Emperor will teach the North discipline."
    },
    "ne_nauzicaa_2": {
        "name": "Nausicaa Cavalry Rider",
        "id": 88,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_2",
        "count": "1",
        "target": "ne_nauzicaa",
        "quote": "The Emperor will teach the North discipline."
    },
    "ne_nauzicaa_3": {
        "name": "Nausicaa Cavalry Rider",
        "id": 89,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_3",
        "count": "1",
        "target": "ne_nauzicaa",
        "quote": "The Emperor will teach the North discipline."
    },
    "ne_puttkammer": {
        "name": "Puttkammer",
        "id": 90,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "3",
        "ability": "",
        "filename": "puttkammer",
        "count": "1",
        "quote": "Learned a lot at Braibant Military Academy. How to scrub potatoes, for instance."
    },
    "ne_rainfarn": {
        "name": "Rainfarn",
        "id": 91,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "rainfarn",
        "count": "1",
        "quote": "You'll die as painfully as the pathetic traitor Windhalm did."
    },
    "ne_renuald": {
        "name": "Renuald aep Matsen",
        "id": 92,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "renuald",
        "count": "1",
        "quote": "They say the Impera fear nothing. Untrue. Renuald scares them shitless."
    },
    "ne_rotten": {
        "name": "Rotten Mangonel",
        "id": 93,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "3",
        "ability": "",
        "filename": "rotten",
        "count": "1",
        "quote": "The rotten smell brings back childhood memories."
    },
    "ne_shilard": {
        "name": "Shilard Fitz-Oesterlen",
        "id": 94,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "7",
        "ability": "spy",
        "filename": "shilard",
        "count": "1",
        "quote": "Warfare is mere sound and fury - diplomacy is what truly shapes history."
    },
    "ne_siege_engineer": {
        "name": "Siege Engineer",
        "id": 95,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "siege_engineer",
        "count": "1",
        "quote": "Wielded correctly, a protactor can be a deadly weapon."
    },
    "ne_siege_support": {
        "name": "Siege Technician",
        "id": 96,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "0",
        "ability": "medic",
        "filename": "siege_support",
        "count": "1",
        "quote": "I never miss twice."
    },
    "ne_stefan": {
        "name": "Stefan Skellen",
        "id": 97,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "9",
        "ability": "spy",
        "filename": "stefan",
        "count": "1",
        "quote": "My mark scards the face of our future empress. That is my proudest achievement."
    },
    "ne_sweers": {
        "name": "Sweers",
        "id": 98,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "sweers",
        "count": "1",
        "quote": "And hands off the girl! Whatever we may be, we're not savages."
    },
    "ne_tibor": {
        "name": "Tibor Eggebracht",
        "id": 99,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "tibor",
        "count": "1",
        "quote": "Albaaaa! Forward!! Alba! Long live the Emperor!"
    },
    "ne_vanhemar": {
        "name": "Vanhemar",
        "id": 100,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "vanhemar",
        "count": "1",
        "quote": "For a fire mage, he's not very... flamboyant."
    },
    "ne_vattier": {
        "name": "Vattier de Rideaux",
        "id": 101,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "4",
        "ability": "spy",
        "filename": "vattier",
        "count": "1",
        "quote": "There's never been a problem a well-planned assassination couldn't solve."
    },
    "ne_vreemde": {
        "name": "Vreemde",
        "id": 102,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "vreemde",
        "count": "1",
        "quote": "Discipline is the Empire's deadliest weapon."
    },
    "ne_young_emissary_1": {
        "name": "Young Emissary",
        "id": 103,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "5",
        "ability": "bond",
        "filename": "young_emissary_1",
        "count": "1",
        "target": "ne_young_emissary",
        "quote": "If I acquit myself well, perhaps next they'll post me somewhere more civilized."
    },
    "ne_young_emissary_2": {
        "name": "Young Emissary",
        "id": 104,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "5",
        "ability": "bond",
        "filename": "young_emissary_2",
        "count": "1",
        "target": "ne_young_emissary",
        "quote": "If I acquit myself well, perhaps next they'll post me somewhere more civilized."
    },
    "ne_zerri": {
        "name": "Zerrikanian Fire Scorpion",
        "id": 105,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "5",
        "ability": "",
        "filename": "zerri",
        "count": "1",
        "quote": "The Zerrikanian Desert used to be a lush garden. Then these came along."
    },
    "mo_eredin_commander": {
        "name": "Eredin - Commander of the Red Riders",
        "id": 106,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_commander",
        "filename": "eredin_commander",
        "count": "1",
        "quote": "Go on. Show me your spins, pirouettes and feints. I want to watch."
    },
    "mo_eredin_bringer_of_death": {
        "name": "Eredin - Bringer of Death",
        "id": 107,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_bringer_of_death",
        "filename": "eredin_bringer_of_death",
        "count": "1",
        "quote": "It is unavoidable."
    },
    "mo_eredin_destroyer": {
        "name": "Eredin - Destroyer of Worlds",
        "id": 108,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_destroyer",
        "filename": "eredin_destroyer",
        "count": "1",
        "quote": "I've long awaited this..."
    },
    "mo_eredin_king": {
        "name": "Eredin - King of the Wild Hunt",
        "id": 109,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_king",
        "filename": "eredin_king",
        "count": "1",
        "quote": "Have some dignity. You know how this will end."
    },
    "mo_eredin_the_treacherous": {
        "name": "Eredin Bréacc Glas - The Treacherous",
        "id": 110,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_treacherous",
        "filename": "eredin_the_treacherous",
        "count": "1",
        "quote": "I'm enjoying this. You are my toy."
    },
    "mo_arachas": {
        "name": "Arachas ",
        "id": 111,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas",
        "count": "1",
        "target": "mo_arachas",
        "quote": "Ugly - nature's way of saying 'Stay the fuck away'"
    },
    "mo_arachas_1": {
        "name": "Arachas ",
        "id": 112,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas_1",
        "count": "1",
        "target": "mo_arachas",
        "quote": "Ugly - nature's way of saying 'Stay the fuck away'"
    },
    "mo_arachas_2": {
        "name": "Arachas ",
        "id": 113,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas_2",
        "count": "1",
        "target": "mo_arachas",
        "quote": "Ugly - nature's way of saying 'Stay the fuck away'"
    },
    "mo_arachas_behemoth": {
        "name": "Arachas- Behemoth",
        "id": 114,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "muster",
        "filename": "arachas_behemoth",
        "count": "1",
        "target": "mo_arachas",
        "quote": "Like a cross between a crab, a spider... and a ploughin' moutain."
    },
    "mo_poroniec": {
        "name": "Botchling",
        "id": 115,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "poroniec",
        "count": "1",
        "quote": "Admit your mistakes and bury them proper - else they'll come back to haunt you."
    },
    "mo_celaeno_harpy": {
        "name": "Celaeno Harpy",
        "id": 116,
        "deck": "monsters",
        "row": "agile",
        "strength": "2",
        "ability": "",
        "filename": "celaeno_harpy",
        "count": "1",
        "quote": "Common harpies feed on carrion. Calaeno harpies... they feed on dreams."
    },
    "mo_cockatrice": {
        "name": "Cockatrice",
        "id": 117,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "cockatrice",
        "count": "1",
        "quote": "Born of an egg laid by a cockerel... if you believe such peasant drivel."
    },
    "mo_witch_velen": {
        "name": "Crone - Brewess",
        "id": 118,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen",
        "count": "1",
        "target": "mo_witch_velen",
        "quote": "We'll cut you up, boy. A fina broth you will make."
    },
    "mo_witch_velen_1": {
        "name": "Crone - Weavess",
        "id": 119,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen_1",
        "count": "1",
        "target": "mo_witch_velen",
        "quote": "I sense your pain. I see your fear..."
    },
    "mo_witch_velen_2": {
        "name": "Crone - Whispess",
        "id": 120,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen_2",
        "count": "1",
        "target": "mo_witch_velen",
        "quote": "I'l be your best - and last."
    },
    "mo_draug": {
        "name": "Draug",
        "id": 121,
        "deck": "monsters",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "draug",
        "count": "1",
        "quote": "Some men cannot admit defeat. Some keep fighting from beyond the grave."
    },
    "mo_earth_elemental": {
        "name": "Earth Elemental",
        "id": 122,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "earth_elemental",
        "count": "1",
        "quote": "How to fight an earth elemental? You don't. You run. Fast as you can."
    },
    "mo_endrega": {
        "name": "Endrega",
        "id": 123,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "endrega",
        "count": "1",
        "quote": "The nest! Take out the nest, or the bastard'll just keep coming!"
    },
    "mo_fiend": {
        "name": "Fiend",
        "id": 124,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "fiend",
        "count": "1",
        "quote": "A fiend looks like a deer. An enormous, evil deer."
    },
    "mo_fire_elemental": {
        "name": "Fire Elemental",
        "id": 125,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "fire_elemental",
        "count": "1",
        "quote": "Fire is so delightful."
    },
    "mo_fogling": {
        "name": "Foglet",
        "id": 126,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "fogling",
        "count": "1",
        "quote": "Fog creeps on little cat feet. Foglets creep over the bodies of their victims."
    },
    "mo_forktail": {
        "name": "Forktail",
        "id": 127,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "forktail",
        "count": "1",
        "quote": "Fork tail.. Bah! Fuckers' tails're more like cleavers."
    },
    "mo_frightener": {
        "name": "Frightener",
        "id": 128,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "frightener",
        "count": "1",
        "quote": "'What have I done?' the mage cried out, frightened of his own creation."
    },
    "mo_gargoyle": {
        "name": "Gargoyle",
        "id": 129,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "gargoyle",
        "count": "1",
        "quote": "Ancient sculptors' nightmarish fantasies brought to life by bored mages."
    },
    "mo_ghoul": {
        "name": "Ghoul",
        "id": 130,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul",
        "count": "1",
        "target": "mo_ghoul",
        "quote": "If ghouls are part of the Circle of Life... then it's a damn vicious circle."
    },
    "mo_ghoul_1": {
        "name": "Ghoul",
        "id": 131,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul_1",
        "count": "1",
        "target": "mo_ghoul",
        "quote": "If ghouls are part of the Circle of Life... then it's a damn vicious circle."
    },
    "mo_ghoul_2": {
        "name": "Ghoul",
        "id": 132,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul_2",
        "count": "1",
        "target": "mo_ghoul",
        "quote": "If ghouls are part of the Circle of Life... then it's a damn vicious circle."
    },
    "mo_gravehag": {
        "name": "Grave Hag",
        "id": 133,
        "deck": "monsters",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "gravehag",
        "count": "1",
        "quote": "Their long tongues're for slurping marrow - and whipping prey."
    },
    "mo_gryffin": {
        "name": "Griffin",
        "id": 134,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "gryffin",
        "count": "1",
        "quote": "Griffins like to toy with their prey. Eat 'em alive, piece by piece."
    },
    "mo_harpy": {
        "name": "Harpy",
        "id": 135,
        "deck": "monsters",
        "row": "agile",
        "strength": "2",
        "ability": "",
        "filename": "harpy",
        "count": "1",
        "quote": "There are many species of harpy, and all are klepmaniacs."
    },
    "mo_frost_giant": {
        "name": "Ice Giant",
        "id": 136,
        "deck": "monsters",
        "row": "siege",
        "strength": "5",
        "ability": "",
        "filename": "frost_giant",
        "count": "1",
        "quote": "Fled one time in my life. From the Ice Giant. And I'm not a bit ashamed."
    },
    "mo_imlerith": {
        "name": "Imlerith",
        "id": 137,
        "deck": "monsters",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "imlerith",
        "count": "1",
        "quote": "Ladd nahw! Kill them! Litter the earth with their entrails!"
    },
    "mo_kayran": {
        "name": "Kayran",
        "id": 138,
        "deck": "monsters",
        "row": "agile",
        "strength": "8",
        "ability": "hero morale",
        "filename": "kayran",
        "count": "1",
        "quote": "Kill a kayran? Simple. Take your best sword... then sell it and hire a witcher."
    },
    "mo_leshen": {
        "name": "Leshen",
        "id": 139,
        "deck": "monsters",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "leshen",
        "count": "1",
        "quote": "We never hunt in these woods. Not even if it means the whole village starves."
    },
    "mo_nekker": {
        "name": "Nekker",
        "id": 140,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker",
        "count": "1",
        "target": "mo_nekker",
        "quote": "Damn things are almost cute, if you ignore the whole vicious killer aspect."
    },
    "mo_nekker_1": {
        "name": "Nekker",
        "id": 141,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker_1",
        "count": "1",
        "target": "mo_nekker",
        "quote": "Damn things are almost cute, if you ignore the whole vicious killer aspect."
    },
    "mo_nekker_2": {
        "name": "Nekker",
        "id": 142,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker_2",
        "count": "1",
        "target": "mo_nekker",
        "quote": "Damn things are almost cute, if you ignore the whole vicious killer aspect."
    },
    "mo_mighty_maiden": {
        "name": "Plague Maiden",
        "id": 143,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mighty_maiden",
        "count": "1",
        "quote": "The sick rave about a boil-pocked woman surrounded by herds of rabid rats..."
    },
    "mo_bruxa": {
        "name": "Vampire - Bruxa",
        "id": 144,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "bruxa",
        "count": "1",
        "target": "mo_vampire",
        "quote": "A vile, bloodthirsty, man-eating hag. Kind of like my mother-in-law."
    },
    "mo_ekkima": {
        "name": "Vampire - Ekimmara",
        "id": 145,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "ekkima",
        "count": "1",
        "target": "mo_vampire",
        "quote": "Who would think overgrown bats would have a taste for gaudy jewelry?"
    },
    "mo_fleder": {
        "name": "Vampire - Fleder",
        "id": 146,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "fleder",
        "count": "1",
        "target": "mo_vampire",
        "quote": "Higher vampieres embrace their victims. Fleders rim them to shreds."
    },
    "mo_garkain": {
        "name": "Vampire - Garkain",
        "id": 147,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "garkain",
        "count": "1",
        "target": "mo_vampire",
        "quote": "Blood-drinkers and corpse-eaters so foul their very ugliness paralyses foes."
    },
    "mo_katakan": {
        "name": "Vampire - Katakan",
        "id": 148,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "katakan",
        "count": "1",
        "target": "mo_vampire",
        "quote": "Drinking the blood of the Continent since the Conjunction."
    },
    "mo_werewolf": {
        "name": "Werewolf",
        "id": 149,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "werewolf",
        "count": "1",
        "quote": "Wolves aren't as bad as they say. Werewolves, though - they're worse."
    },
    "mo_wyvern": {
        "name": "Wyvern",
        "id": 150,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "wyvern",
        "count": "1",
        "quote": "Imagine a cross between a winged snake and a nightmare. Wyverns are worse."
    },
    "mo_toad": {
        "name": "Toad",
        "id": 151,
        "deck": "monsters",
        "row": "ranged",
        "strength": "7",
        "ability": "scorch_r",
        "filename": "toad",
        "count": "1",
        "quote": "Big. Bad. Ugly. Squats in the sewers."
    },
    "sc_francesca_queen": {
        "name": "Francesca Findabair - Queen of Dol Blathanna",
        "id": 152,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_queen",
        "filename": "francesca_queen",
        "count": "1",
        "quote": "Ash shall fertilize the soil. By spring, the valley shall bloom once more."
    },
    "sc_francesca_beautiful": {
        "name": "Francesca Findabair - the Beautiful",
        "id": 153,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_beautiful",
        "filename": "francesca_beautiful",
        "count": "1",
        "quote": "The Elder Races have forgotten more than humans can ever hope to know."
    },
    "sc_francesca_daisy": {
        "name": "Francesca Findabair - Daisy of the Valley",
        "id": 154,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_daisy",
        "filename": "francesca_daisy",
        "count": "1",
        "quote": "Do not let my beauty distract your aim."
    },
    "sc_francesca_pureblood": {
        "name": "Francesca Findabair - Pureblood Elf",
        "id": 155,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_pureblood",
        "filename": "francesca_pureblood",
        "count": "1",
        "quote": "To live in peave, we first must kill. This is human oppression's cruel finale."
    },
    "sc_francesca_hope_of_the_aen_seidhe": {
        "name": "Francesca Findabair - Hope of the Aen Seidhe",
        "id": 156,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_hope",
        "filename": "francesca_hope_of_the_aen_seidhe",
        "count": "1",
        "quote": "Daede sian caente, Aen Seidhe en'allane ael coeden..."
    },
    "sc_ciaran": {
        "name": "Ciaran aep Easnillien",
        "id": 157,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "3",
        "ability": "",
        "filename": "ciaran",
        "count": "1",
        "quote": "The path to freedom is paved in blood not ink."
    },
    "sc_barclay": {
        "name": "Barclay Els",
        "id": 158,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "barclay",
        "count": "1",
        "quote": "Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!"
    },
    "sc_dennis": {
        "name": "Dennis Cranmer",
        "id": 159,
        "deck": "scoiatael",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "dennis",
        "count": "1",
        "quote": "I know how to carry out orders, so you can shove you advice up your coal chute."
    },
    "sc_dol_archer": {
        "name": "Dol Blathanna Archer",
        "id": 160,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "dol_archer",
        "count": "1",
        "quote": "Take another step, dh'oine. You'd look better with an arrow between your eyes."
    },
    "sc_dol_infantry": {
        "name": "Dol Blathanna Scout",
        "id": 161,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry",
        "count": "1",
        "quote": "They track like hounds, run like deer and kill like cold-hearted bastards."
    },
    "sc_dol_infantry_1": {
        "name": "Dol Blathanna Scout",
        "id": 162,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry_1",
        "count": "1",
        "quote": "They track like hounds, run like deer and kill like cold-hearted bastards."
    },
    "sc_dol_infantry_2": {
        "name": "Dol Blathanna Scout",
        "id": 163,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry_2",
        "count": "1",
        "quote": "They track like hounds, run like deer and kill like cold-hearted bastards."
    },
    "sc_dwarf": {
        "name": "Dwarven Skirmisher",
        "id": 164,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf",
        "count": "1",
        "target": "sc_dwarf",
        "quote": "Worked a pickaxe all me life. Battleaxe won't be any trouble."
    },
    "sc_dwarf_1": {
        "name": "Dwarven Skirmisher",
        "id": 165,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf_1",
        "count": "1",
        "target": "sc_dwarf",
        "quote": "Worked a pickaxe all me life. Battleaxe won't be any trouble."
    },
    "sc_dwarf_2": {
        "name": "Dwarven Skirmisher",
        "id": 166,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf_2",
        "count": "1",
        "target": "sc_dwarf",
        "quote": "Worked a pickaxe all me life. Battleaxe won't be any trouble."
    },
    "sc_eithne": {
        "name": "Eithné",
        "id": 167,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "eithne",
        "count": "1",
        "quote": "The dryad queen has eyes of molten silver, and a heart of cold-forged steel."
    },
    "sc_elf_skirmisher": {
        "name": "Elven Skirmisher",
        "id": 168,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher",
        "count": "1",
        "target": "sc_elf_skirmisher",
        "quote": "No matter what you may have heard, elves don't take human scalps. Too much lice."
    },
    "sc_elf_skirmisher_1": {
        "name": "Elven Skirmisher",
        "id": 169,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher_1",
        "count": "1",
        "target": "sc_elf_skirmisher",
        "quote": "No matter what you may have heard, elves don't take human scalps. Too much lice."
    },
    "sc_elf_skirmisher_2": {
        "name": "Elven Skirmisher",
        "id": 170,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher_2",
        "count": "1",
        "target": "sc_elf_skirmisher",
        "quote": "No matter what you may have heard, elves don't take human scalps. Too much lice."
    },
    "sc_filavandrel": {
        "name": "Filavandrel aen Fidhail",
        "id": 171,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "filavandrel",
        "count": "1",
        "quote": "Though we are now few and scattered, our hearts burn brighter than ever."
    },
    "sc_havekar_nurse": {
        "name": "Havekar Healer",
        "id": 172,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse",
        "count": "1",
        "quote": "Sure, I'll patch you up. Gonna cost you, though."
    },
    "sc_havekar_nurse_1": {
        "name": "Havekar Healer",
        "id": 173,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse_1",
        "count": "1",
        "quote": "Sure, I'll patch you up. Gonna cost you, though."
    },
    "sc_havekar_nurse_2": {
        "name": "Havekar Healer",
        "id": 174,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse_2",
        "count": "1",
        "quote": "Sure, I'll patch you up. Gonna cost you, though."
    },
    "sc_havekar_support": {
        "name": "Havekar Smuggler",
        "id": 175,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support",
        "count": "1",
        "target": "sc_havekar_support",
        "quote": "I fight for whoever's paying the best. Or whoever's easiest to rob."
    },
    "sc_havekar_support_1": {
        "name": "Havekar Smuggler",
        "id": 176,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support_1",
        "count": "1",
        "target": "sc_havekar_support",
        "quote": "I fight for whoever's paying the best. Or whoever's easiest to rob."
    },
    "sc_havekar_support_2": {
        "name": "Havekar Smuggler",
        "id": 177,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support_2",
        "count": "1",
        "target": "sc_havekar_support",
        "quote": "I fight for whoever's paying the best. Or whoever's easiest to rob."
    },
    "sc_ida": {
        "name": "Ida Emean aep Sivney",
        "id": 178,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "ida",
        "count": "1",
        "quote": "I am a Sage. My power lies in possessing knowledge. Not sharing it."
    },
    "sc_iorveth": {
        "name": "Iorveth",
        "id": 179,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "iorveth",
        "count": "1",
        "quote": "King or beggar, what's the difference? One dh'oine less."
    },
    "sc_isengrim": {
        "name": "Isengrim Faoiltiarna",
        "id": 180,
        "deck": "scoiatael",
        "row": "close",
        "strength": "10",
        "ability": "hero morale",
        "filename": "isengrim",
        "count": "1",
        "quote": "It dawns on them once they notice my scar: a realization of imminent death."
    },
    "sc_mahakam": {
        "name": "Mahakaman Defender",
        "id": 181,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam",
        "count": "1",
        "quote": "I'm telling ye, we're born for battle - we slash straight at their kneed!"
    },
    "sc_mahakam_1": {
        "name": "Mahakaman Defender",
        "id": 182,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_1",
        "count": "1",
        "quote": "I'm telling ye, we're born for battle - we slash straight at their kneed!"
    },
    "sc_mahakam_2": {
        "name": "Mahakaman Defender",
        "id": 183,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_2",
        "count": "1",
        "quote": "I'm telling ye, we're born for battle - we slash straight at their kneed!"
    },
    "sc_mahakam_3": {
        "name": "Mahakaman Defender",
        "id": 184,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_3",
        "count": "1",
        "quote": "I'm telling ye, we're born for battle - we slash straight at their kneed!"
    },
    "sc_mahakam_4": {
        "name": "Mahakaman Defender",
        "id": 185,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_4",
        "count": "1",
        "quote": "I'm telling ye, we're born for battle - we slash straight at their kneed!"
    },
    "sc_milva": {
        "name": "Milva",
        "id": 186,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "morale",
        "filename": "milva",
        "count": "1",
        "quote": "With each arrow I loose, I think of my da. He'd be proud. I think."
    },
    "sc_riordain": {
        "name": "Riordain",
        "id": 187,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "1",
        "ability": "",
        "filename": "riordain",
        "count": "1",
        "quote": "Stare into their eyes, feast on their terror. Then go in for the kill."
    },
    "sc_saskia": {
        "name": "Saesenthessis",
        "id": 188,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "saskia",
        "count": "1",
        "quote": "Beautiful, pure, fierce - the perfect icon for a rebellion."
    },
    "sc_toruviel": {
        "name": "Toruviel",
        "id": 189,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "toruviel",
        "count": "1",
        "quote": "I'd gladly kill you from up close, stare in your eyese... But you reek, human."
    },
    "sc_vrihedd_cadet": {
        "name": "Vrihedd Brigade Recruit",
        "id": 190,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "vrihedd_cadet",
        "count": "1",
        "quote": "Hatred burns brighter than any fire, and cuts deeper than any blade."
    },
    "sc_vrihedd_brigade": {
        "name": "Vrihedd Brigade Veteran",
        "id": 191,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "5",
        "ability": "",
        "filename": "vrihedd_brigade",
        "count": "1",
        "quote": "'Vrihedd? What's that mean?' 'Trouble.'"
    },
    "sc_vrihedd_brigade_1": {
        "name": "Vrihedd Brigade Veteran",
        "id": 192,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "5",
        "ability": "",
        "filename": "vrihedd_brigade_1",
        "count": "1",
        "quote": "'Vrihedd? What's that mean?' 'Trouble.'"
    },
    "sc_yaevinn": {
        "name": "Yaevinn",
        "id": 193,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "yaevinn",
        "count": "1",
        "quote": "We are drops of rain that together make a ferocious storm."
    },
    "sk_berserker": {
        "name": "Berserker",
        "id": 194,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "berserker",
        "filename": "berserker",
        "count": "1",
        "target": "sk_vildkaarl",
        "quote": "Kill, crush, cleave!"
    },
    "sk_birna": {
        "name": "Birna Bran",
        "id": 195,
        "deck": "skellige",
        "row": "close",
        "strength": "2",
        "ability": "medic",
        "filename": "birna",
        "count": "1",
        "quote": "Skellige must have a strong king. No matter what it takes."
    },
    "sk_blueboy": {
        "name": "Blueboy Lugos",
        "id": 196,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "blueboy",
        "count": "1",
        "quote": "I'm damn near ready to puke from boredom."
    },
    "sk_cerys": {
        "name": "Cerys",
        "id": 197,
        "deck": "skellige",
        "row": "close",
        "strength": "10",
        "ability": "hero muster",
        "filename": "cerys",
        "count": "1",
        "target": "sk_shield_maiden",
        "quote": "They call me Sparrowhawk, know why? Because I eat rats like you for breakfast."
    },
    "sk_brokva_archer": {
        "name": "Clan Brokvar Archer",
        "id": 198,
        "deck": "skellige",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "brokva_archer",
        "count": "2",
        "quote": "So ye can hit a movin' target at two hundred paces. Me, too. In a storm."
    },
    "sk_dimun_pirate": {
        "name": "Clan Dimun Pirate",
        "id": 199,
        "deck": "skellige",
        "row": "ranged",
        "strength": "6",
        "ability": "scorch",
        "filename": "dimun_pirate",
        "count": "1",
        "quote": "Can see the fear in their eyes. Fear o' me... fer o' Clan Dimun!"
    },
    "sk_shield_maiden_1": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 200,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_1",
        "count": "1",
        "target": "sk_shield_maiden",
        "quote": "They'll shatter on our shields like waves on a rocky shore."
    },
    "sk_shield_maiden_2": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 201,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_2",
        "count": "1",
        "target": "sk_shield_maiden",
        "quote": "They'll shatter on our shields like waves on a rocky shore."
    },
    "sk_shield_maiden_3": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 202,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_3",
        "count": "1",
        "target": "sk_shield_maiden",
        "quote": "They'll shatter on our shields like waves on a rocky shore."
    },
    "sk_heymaey": {
        "name": "Clan Heymaey Skald",
        "id": 203,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "heymaey",
        "count": "1",
        "quote": "The deeds of Clan Haymaeu will go down in history."
    },
    "sk_tordarroch": {
        "name": "Clan Tordarroch Armorsmith",
        "id": 204,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "tordarroch",
        "count": "1",
        "quote": "Ye're in for poundin'."
    },
    "sk_craite_warrior_1": {
        "name": "Clan an Craite Warrior",
        "id": 205,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_1",
        "count": "1",
        "target": "sk_craite_warrior",
        "quote": "I'll bring the an Craites such glory, bards'll go hoarse singin' me praises!"
    },
    "sk_craite_warrior_2": {
        "name": "Clan an Craite Warrior",
        "id": 206,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_2",
        "count": "1",
        "target": "sk_craite_warrior",
        "quote": "I'll bring the an Craites such glory, bards'll go hoarse singin' me praises!"
    },
    "sk_craite_warrior_3": {
        "name": "Clan an Craite Warrior",
        "id": 207,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_3",
        "count": "1",
        "target": "sk_craite_warrior",
        "quote": "I'll bring the an Craites such glory, bards'll go hoarse singin' me praises!"
    },
    "sk_donar": {
        "name": "Donar an Hindar",
        "id": 208,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "donar",
        "count": "1",
        "quote": "I've gathered all the jarls together. Now make your case."
    },
    "sk_draig": {
        "name": "Draig Bon-Dhu",
        "id": 209,
        "deck": "skellige",
        "row": "siege",
        "strength": "2",
        "ability": "horn",
        "filename": "draig",
        "count": "1",
        "quote": "Hear ye now the tale of the heroic deeds of Clan an Craite."
    },
    "sk_ermion": {
        "name": "Ermion",
        "id": 210,
        "deck": "skellige",
        "row": "ranged",
        "strength": "8",
        "ability": "hero mardroeme",
        "filename": "ermion",
        "count": "1",
        "quote": "Only the ignorant dismiss the importance of myths."
    },
    "sk_hemdall": {
        "name": "Hemdall",
        "id": 211,
        "deck": "skellige",
        "row": "close",
        "strength": "11",
        "ability": "hero",
        "filename": "hemdall",
        "count": "0",
        "quote": "When the time of the White Frost comes, Hemdall will sound the call for battle."
    },
    "sk_hjalmar": {
        "name": "Hjalmar",
        "id": 212,
        "deck": "skellige",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "hjalmar",
        "count": "1",
        "quote": "Instead of mournin' the fallen, let's drink to their memory!"
    },
    "sk_holger": {
        "name": "Holger Blackhand",
        "id": 213,
        "deck": "skellige",
        "row": "siege",
        "strength": "4",
        "ability": "",
        "filename": "holger",
        "count": "1",
        "quote": "Now let's drink to Emperor of Nilfgaard - may his prick forever stay limp!"
    },
    "sk_kambi": {
        "name": "Kambi",
        "id": 214,
        "deck": "skellige",
        "row": "close",
        "strength": "0",
        "ability": "avenger_kambi",
        "filename": "kambi",
        "count": "1",
        "target": "sk_hemdall",
        "quote": "When the time comes, the cockerel Kambi shall crow and awaken Hemdall."
    },
    "sk_light_longship": {
        "name": "Light Longship",
        "id": 215,
        "deck": "skellige",
        "row": "ranged",
        "strength": "4",
        "ability": "muster",
        "filename": "light_longship",
        "count": "3",
        "target": "sk_light_longship",
        "quote": "Escape them? In the waters of Skellige? Good luck."
    },
    "sk_madmad_lugos": {
        "name": "Madman Lugos",
        "id": 216,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "madmad_lugos",
        "count": "1",
        "quote": "WAAAAAAAGH!!!!"
    },
    "spe_mardroeme": {
        "name": "Mardroeme",
        "id": 217,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "mardroeme",
        "filename": "mardroeme",
        "count": "3",
        "quote": "Eat enough of them, and the world will never be the same..."
    },
    "sk_olaf": {
        "name": "Olaf",
        "id": 218,
        "deck": "skellige",
        "row": "agile",
        "strength": "12",
        "ability": "morale",
        "filename": "olaf",
        "count": "1",
        "quote": "Many've tried to defeat Olaf. But wont' hear about it from them - they're dead."
    },
    "spe_storm": {
        "name": "Skellige Storm",
        "id": 219,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "rain fog",
        "filename": "storm",
        "count": "3",
        "quote": "This ain't no normal storm. This here's the wrath of the gods."
    },
    "sk_svanrige": {
        "name": "Svanrige",
        "id": 220,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "svanrige",
        "count": "1",
        "quote": "The emperor also thought him an accidental king. At first."
    },
    "sk_vildkaarl": {
        "name": "Transformed Vildkaarl",
        "id": 221,
        "deck": "skellige",
        "row": "close",
        "strength": "14",
        "ability": "morale",
        "filename": "vildkaarl",
        "count": "0",
        "quote": "Saw them fight once in my life... and once was enough."
    },
    "sk_young_vildkaarl": {
        "name": "Transformed Young Vildkaarl",
        "id": 222,
        "deck": "skellige",
        "row": "ranged",
        "strength": "8",
        "ability": "bond",
        "filename": "young_vildkaarl",
        "count": "0",
        "target": "sk_young_vildkaarl",
        "quote": "Rooaaar!"
    },
    "sk_udalryk": {
        "name": "Udalryk",
        "id": 223,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "udalryk",
        "count": "1",
        "quote": "Haaaargh! After me, if ye've the bollocks!"
    },
    "sk_war_longship_1": {
        "name": "War Longship",
        "id": 224,
        "deck": "skellige",
        "row": "siege",
        "strength": "6",
        "ability": "bond",
        "filename": "war_longship_1",
        "count": "1",
        "target": "sk_war_longship",
        "quote": "They say Hemdall's heart swells whenever the longships sail out on a raid."
    },
    "sk_war_longship_2": {
        "name": "War Longship",
        "id": 225,
        "deck": "skellige",
        "row": "siege",
        "strength": "6",
        "ability": "bond",
        "filename": "war_longship_2",
        "count": "1",
        "target": "sk_war_longship",
        "quote": "They say Hemdall's heart swells whenever the longships sail out on a raid."
    },
    "sk_young_berserker": {
        "name": "Young Berserker",
        "id": 226,
        "deck": "skellige",
        "row": "ranged",
        "strength": "2",
        "ability": "berserker",
        "filename": "young_berserker",
        "count": "3",
        "target": "sk_young_vildkaarl",
        "quote": "Want some?"
    },
    "sk_crach_an_craite": {
        "name": "Crach an Craite",
        "id": 227,
        "deck": "skellige",
        "row": "leader",
        "strength": "",
        "ability": "crach_an_craite",
        "filename": "crach_an_craite",
        "count": "0",
        "quote": "A king's gotta be wise. A king's gotta command respect. A king's gotta have stones."
    },
    "sk_king_bran": {
        "name": "King Bran",
        "id": 228,
        "deck": "skellige",
        "row": "leader",
        "strength": "",
        "ability": "king_bran",
        "filename": "king_bran",
        "count": "0",
        "quote": "No one can replace Bran. Though they're sure to try."
    },
    "sc_schirru": {
        "name": "Schirru",
        "id": 229,
        "deck": "scoiatael",
        "row": "siege",
        "strength": "8",
        "ability": "scorch_s",
        "filename": "schirru",
        "count": "1",
        "quote": "Time to look death in the face."
    }
};

/*
 * Custom new cards
 */


var ext_nr_cards = {
    "nr_foltest_pride": {
        "name": "Foltest's Pride",
        "id": 1001,
        "deck": "realms",
        "row": "siege",
        "strength": "9",
        "ability": "",
        "filename": "foltest_pride",
        "count": "1",
        "quote": "As King Foltest likes to say, it's not size that count, but whether it gets the job done."
    },
    "nr_temerian_soldier_1": {
        "name": "Temerian Foot Solider",
        "id": 1002,
        "deck": "realms",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "temerian_soldier_1",
        "count": "1",
        "quote": "Temeria! Gods shed all grace on thee! And smite thy foes with horrid woes, for all eternity!"
    },
    "nr_temerian_soldier_2": {
        "name": "Temerian Foot Solider",
        "id": 1003,
        "deck": "realms",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "temerian_soldier_2",
        "count": "1",
        "quote": "Temeria! Gods shed all grace on thee! And smite thy foes with horrid woes, for all eternity!"
    },
    "nr_temerian_soldier_3": {
        "name": "Temerian Foot Solider",
        "id": 1004,
        "deck": "realms",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "temerian_soldier_3",
        "count": "1",
        "quote": "Temeria! Gods shed all grace on thee! And smite thy foes with horrid woes, for all eternity!"
    },
    "nr_reaver_scout": {
        "name": "Reaver Scout",
        "id": 1005,
        "deck": "realms",
        "row": "ranged",
        "strength": "6",
        "ability": "spy",
        "filename": "reaver_scout",
        "count": "1",
        "quote": "Haven't had much luck with monsters of late, so we enlisted."
    },
    "nr_temerian_drummer": {
        "name": "Temerian Drummer",
        "id": 1006,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "horn",
        "filename": "temerian_drummer",
        "count": "1",
        "quote": "Not the career he had in mind when he told mummy he wanted to be a musician."
    },
    "nr_stripes_scout": {
        "name": "Blue Stripes Scout",
        "id": 1007,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "scorch",
        "filename": "stripes_scout",
        "count": "1",
        "quote": "Blue Stripes and Scoia'Tael are similar in one regard - hatred fuels both."
    },
    "nr_tridam_infantry": {
        "name": "Tridam Infantry",
        "id": 1008,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "tridam_infantry",
        "count": "1",
        "quote": "Soldiers loyal to the old baron of Tridam left the city with Falibor..."
    },
    "nr_vandergrift": {
        "name": "Vandergrift",
        "id": 1009,
        "deck": "realms",
        "row": "ranged",
        "strength": "9",
        "ability": "hero",
        "filename": "vandergrift",
        "count": "1",
        "quote": "What has that witch done?!"
    },
    "nr_kaedweni_siege_support_1": {
        "name": "Kaedweni Siege Support",
        "id": 1010,
        "deck": "realms",
        "row": "siege",
        "strength": "2",
        "ability": "morale",
        "filename": "kaedweni_siege_support_1",
        "count": "1",
        "quote": "I never miss twice."
    },
    "nr_kaedweni_siege_support_2": {
        "name": "Kaedweni Siege Support",
        "id": 1011,
        "deck": "realms",
        "row": "siege",
        "strength": "2",
        "ability": "morale",
        "filename": "kaedweni_siege_support_2",
        "count": "1",
        "quote": "I never miss twice."
    },
    "nr_henselt": {
        "name": "Henselt",
        "id": 1012,
        "deck": "realms",
        "row": "siege",
        "strength": "10",
        "ability": "hero",
        "filename": "henselt",
        "count": "1",
        "quote": "King Henselt did not look like a thief, but, with all due respect, that's really what he was."
    },
    "nr_kaedweni_reinforcement": {
        "name": "Kaedweni Reinforcement",
        "id": 1013,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "medic",
        "filename": "kaedweni_reinforcement",
        "count": "1",
        "quote": "Sound the retreat! Regroup! And wait for reinforcements!"
    },
    "nr_reinforced_ballista_1": {
        "name": "Reinforced Ballista",
        "id": 1014,
        "deck": "realms",
        "row": "siege",
        "strength": "4",
        "ability": "bond",
        "filename": "reinforced_ballista_1",
        "count": "1",
        "quote": "Never manages to hit the same place twice, which might constitute a real problem."
    },
    "nr_reinforced_ballista_2": {
        "name": "Reinforced Ballista",
        "id": 1015,
        "deck": "realms",
        "row": "siege",
        "strength": "4",
        "ability": "bond",
        "filename": "reinforced_ballista_2",
        "count": "1",
        "quote": "Never manages to hit the same place twice, which might constitute a real problem."
    },
    "nr_reinforced_trebuchet_1": {
        "name": "Reinforced Trebuchet",
        "id": 1016,
        "deck": "realms",
        "row": "siege",
        "strength": "5",
        "ability": "bond",
        "filename": "reinforced_trebuchet_1",
        "count": "1",
        "quote": "Feel that? The earth trembles each time Big Bertha loose a stone."
    },
    "nr_reinforced_trebuchet_2": {
        "name": "Reinforced Trebuchet",
        "id": 1017,
        "deck": "realms",
        "row": "siege",
        "strength": "5",
        "ability": "bond",
        "filename": "reinforced_trebuchet_2",
        "count": "1",
        "quote": "Feel that? The earth trembles each time Big Bertha loose a stone."
    },
    "nr_ban_ard_tutor": {
        "name": "Ban Ard Tutor",
        "id": 1018,
        "deck": "realms",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "ban_ard_tutor",
        "count": "1",
        "quote": "Ban Ard deserved a mention, for it is famous for the school of young adepts of the magical arts."
    },
    "nr_demavend": {
        "name": "Demavend",
        "id": 1019,
        "deck": "realms",
        "row": "siege",
        "strength": "10",
        "ability": "hero",
        "filename": "demavend",
        "count": "1",
        "quote": "War's crux lies in winning, not in being persistent."
    },
    "nr_kaedweni_knight": {
        "name": "Kaedweni Knight",
        "id": 1020,
        "deck": "realms",
        "row": "close",
        "strength": "7",
        "ability": "",
        "filename": "kaedweni_knight",
        "count": "1",
        "quote": "Not every man in the Kaedweni army supports his king's politics..."
    },
    "nr_dun_banner_heavy_cavalry_1": {
        "name": "Dun Banner Heavy Cavalry",
        "id": 1021,
        "deck": "realms",
        "row": "ranged",
        "strength": "7",
        "ability": "",
        "filename": "dun_banner_heavy_cavalry_1",
        "count": "1",
        "quote": "Always wondered... how the blazes do those lads handle nature's call...?"
    },
    "nr_dun_banner_heavy_cavalry_2": {
        "name": "Dun Banner Heavy Cavalry",
        "id": 1022,
        "deck": "realms",
        "row": "ranged",
        "strength": "7",
        "ability": "",
        "filename": "dun_banner_heavy_cavalry_2",
        "count": "1",
        "quote": "Always wondered... how the blazes do those lads handle nature's call...?"
    },
    "nr_odrin": {
        "name": "Odrin",
        "id": 1023,
        "deck": "realms",
        "row": "agile",
        "strength": "3",
        "ability": "morale",
        "filename": "odrin",
        "count": "1",
        "quote": "Drinkin' without Odrin is like rowin' without a paddle."
    },
    "nr_seltkirk": {
        "name": "Seltkirk of Gulet",
        "id": 1024,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "seltkirk",
        "count": "1",
        "quote": "Seltkirk of Gulet was Demavend champion, known as the invincible white knight."
    },
    "nr_kaedweni_sergeant": {
        "name": "Kaedweni Sergeant",
        "id": 1025,
        "deck": "realms",
        "row": "siege",
        "strength": "5",
        "ability": "morale",
        "filename": "kaedweni_sergeant",
        "count": "1",
        "quote": "Forward, you sorry sods! Or you'll see the Nilfgaardians are the least of your worries!"
    },
    "nr_queen_calanthe": {
        "name": "Queen Calanthe: Lioness of Cintra",
        "id": 1026,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "queen_calanthe",
        "filename": "queen_calanthe",
        "count": "1",
        "quote": "They call her the 'Lioness of Cintra'. And not without good reason."
    },
    "nr_viraxas": {
        "name": "Viraxas",
        "id": 1027,
        "deck": "realms",
        "row": "siege",
        "strength": "9",
        "ability": "hero",
        "filename": "viraxas",
        "count": "1",
        "quote": "Revenge is a dish that tastes best when served for two."
    },
    "nr_kerack_fleet_marine_1": {
        "name": "Kerack Fleet: Marine",
        "id": 1028,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "muster",
        "filename": "kerack_fleet_marine_1",
        "count": "1",
        "target": "nr_kerack_fleet",
        "quote": "I spy with my little eye something that is... green. Oh, shite! That's a dryad!"
    },
    "nr_kerack_fleet_marine_2": {
        "name": "Kerack Fleet: Marine",
        "id": 1029,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "muster",
        "filename": "kerack_fleet_marine_2",
        "count": "1",
        "target": "nr_kerack_fleet",
        "quote": "I spy with my little eye something that is... green. Oh, shite! That's a dryad!"
    },
    "nr_kerack_fleet_frigate": {
        "name": "Kerack Fleet: Frigate",
        "id": 1029,
        "deck": "realms",
        "row": "ranged",
        "strength": "4",
        "ability": "muster",
        "filename": "kerack_fleet_frigate",
        "count": "1",
        "target": "nr_kerack_fleet",
        "quote": "'I should buy a boat' said a Kerackian cat once. Or so claims the drunken ballad."
    },
    "nr_vissegerd": {
        "name": "Vissegerd",
        "id": 1030,
        "deck": "realms",
        "row": "close",
        "strength": "7",
        "ability": "",
        "filename": "vissegerd",
        "count": "1",
        "quote": "I will raise Cintra from the ashes no matter how great the cost."
    },
    "nr_cintrian_royal_guard": {
        "name": "Cintrian Royal Guard",
        "id": 1031,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "cintra_slaughter",
        "filename": "cintrian_royal_guard",
        "count": "2",
        "quote": "I will raise Cintra from the ashes no matter how great the cost."
    },
    "spe_slaughther_cintra_1": {
        "name": "Slaughter of Cintra",
        "id": 1032,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "cintra_slaughter",
        "filename": "slaughter_cintra_1",
        "count": "1",
        "quote": "The battle of Cintra, which Nordlings call the Slaughter of Cintra because of the very cruel actions of the Nilfgaardian army."
    },
    "spe_slaughther_cintra_2": {
        "name": "Slaughter of Cintra",
        "id": 1033,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "cintra_slaughter",
        "filename": "slaughter_cintra_2",
        "count": "1",
        "quote": "The battle of Cintra, which Nordlings call the Slaughter of Cintra because of the very cruel actions of the Nilfgaardian army."
    },
    "spe_slaughther_cintra_3": {
        "name": "Slaughter of Cintra",
        "id": 1034,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "cintra_slaughter",
        "filename": "slaughter_cintra_3",
        "count": "1",
        "quote": "The battle of Cintra, which Nordlings call the Slaughter of Cintra because of the very cruel actions of the Nilfgaardian army."
    },
    "nr_eist_tuirseach": {
        "name": "Eist Tuirseach",
        "id": 1035,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero muster",
        "filename": "eist_tuirseach",
        "count": "1",
        "target": "skellige_fleet",
        "quote": "Skellige and Cintra shall stand ever together."
    },
    "nr_skellige_fleet_1": {
        "name": "Skellige Raiders Fleet",
        "id": 1036,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "morale",
        "filename": "skellige_fleet_1",
        "count": "1",
        "target": "skellige_fleet",
        "quote": "The islanders know that there is fertile soil on the other side of the sea..."
    },
    "nr_skellige_fleet_2": {
        "name": "Skellige Raiders Fleet",
        "id": 1037,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "morale",
        "filename": "skellige_fleet_2",
        "count": "1",
        "target": "skellige_fleet",
        "quote": "The islanders know that there is fertile soil on the other side of the sea..."
    },
    "nr_skellige_fleet_3": {
        "name": "Skellige Raiders Fleet",
        "id": 1038,
        "deck": "realms",
        "row": "ranged",
        "strength": "3",
        "ability": "morale",
        "filename": "skellige_fleet_3",
        "count": "1",
        "target": "skellige_fleet",
        "quote": "The islanders know that there is fertile soil on the other side of the sea..."
    },
    "nr_cintrian_knight": {
        "name": "Cintrian Knight",
        "id": 1039,
        "deck": "realms",
        "row": "close",
        "strength": "7",
        "ability": "cintra_slaughter",
        "filename": "cintrian_knight",
        "count": "2",
        "quote": "For whom does the bell toll?"
    },
    "nr_roegner": {
        "name": "Roegner de Salm",
        "id": 1040,
        "deck": "realms",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "roegner",
        "count": "1",
        "quote": "Roegner de Salm was the son of a prince of Salm in Ebbing."
    },
    "nr_pavetta": {
        "name": "Roegner de Salm",
        "id": 1041,
        "deck": "realms",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "pavetta",
        "count": "1",
        "quote": "They said the queen was prone to outbursts but I did not expect that..."
    },
    "nr_kistrin_verden": {
        "name": "Kistrin of Verden",
        "id": 1042,
        "deck": "realms",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "kistrin_verden",
        "count": "1",
        "quote": "Oh dammit. Kistrin? Prince Kistrin? The son of King Ervyll of Verden?"
    },
    "nr_sha": {
        "name": "Sha",
        "id": 1043,
        "deck": "realms",
        "row": "siege",
        "strength": "3",
        "ability": "avenger",
        "filename": "sha",
        "count": "1",
        "target": "nr_kraken",
        "quote": "A noblewoman from beyond the seas."
    },
    "nr_kraken": {
        "name": "Kraken",
        "id": 1044,
        "deck": "realms",
        "row": "ranged",
        "strength": "11",
        "ability": "hero scorch",
        "filename": "kraken",
        "count": "1",
        "quote": "'A kra-kraken?' 'Yes, a kraken' the witcher repeated."
    },
    "nr_egmund": {
        "name": "Egmund",
        "id": 1045,
        "deck": "realms",
        "row": "close",
        "strength": "7",
        "ability": "scorch_c",
        "filename": "egmund",
        "count": "1",
        "quote": "Since father has never appreciated nor trusted Egmund, it was but a simple decision to betray him."
    },
    "nr_eylembert_tigg": {
        "name": "Eylembert of Tigg",
        "id": 1046,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "horn",
        "filename": "eylembert_tigg",
        "count": "1",
        "quote": "'Coodcoodak!' murmured Calanthe. 'This will be fun.'"
    },
    "nr_young_ciri": {
        "name": "Young Ciri",
        "id": 1047,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "avenger",
        "filename": "young_ciri",
        "count": "1",
        "target": "ntr_ciri",
        "quote": "I'm not afraid at all!"
    },
    "nr_cintrian_peasants": {
        "name": "Cintrian Peasants",
        "id": 1048,
        "deck": "realms",
        "row": "close",
        "strength": "3",
        "ability": "cintra_slaughter",
        "filename": "cintrian_peasants",
        "count": "2",
        "quote": "There's a time to reap, at time to sow ...and a time to die."
    },
    "nr_windhalm": {
        "name": "Windhalm of Attre",
        "id": 1049,
        "deck": "realms",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "windhalm",
        "count": "1",
        "quote": "Off with his head! But slowly, drag it out, put on a show for all to see."
    }
};

/*
 * Selecting decks to use
 */
var card_dict = default_cards;

card_dict = Object.assign({}, card_dict, ext_nr_cards);