var card_dict = {
    "ntr_mysterious_elf": {
        "name": "Mysterious Elf",
        "id": 0,
        "deck": "neutral",
        "row": "close",
        "strength": "0",
        "ability": "hero spy",
        "filename": "mysterious_elf",
        "count": "1"
    },
    "spe_decoy": {
        "name": "Decoy",
        "id": 1,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "decoy",
        "filename": "decoy",
        "count": "3"
    },
    "spe_frost": {
        "name": "Biting Frost",
        "id": 2,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "frost",
        "filename": "frost",
        "count": "3"
    },
    "ntr_ciri": {
        "name": "Cirilla Fiona Elen Riannon",
        "id": 3,
        "deck": "neutral",
        "row": "close",
        "strength": "15",
        "ability": "hero",
        "filename": "ciri",
        "count": "1"
    },
    "spe_clear": {
        "name": "Clear Weather",
        "id": 4,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "clear",
        "filename": "clear",
        "count": "2"
    },
    "spe_horn": {
        "name": "Commander's Horn",
        "id": 5,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "horn",
        "filename": "horn",
        "count": "3"
    },
    "ntr_dandelion": {
        "name": "Dandelion",
        "id": 6,
        "deck": "neutral",
        "row": "close",
        "strength": "2",
        "ability": "horn",
        "filename": "dandelion",
        "count": "1"
    },
    "ntr_emiel": {
        "name": "Emiel Regis Rohellec Terzieff",
        "id": 7,
        "deck": "neutral",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "emiel",
        "count": "1"
    },
    "ntr_geralt": {
        "name": "Geralt of Rivia",
        "id": 8,
        "deck": "neutral",
        "row": "close",
        "strength": "15",
        "ability": "hero",
        "filename": "geralt",
        "count": "1"
    },
    "spe_fog": {
        "name": "Impenetrable Fog",
        "id": 9,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "fog",
        "filename": "fog",
        "count": "3"
    },
    "spe_scorch": {
        "name": "Scorch",
        "id": 10,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "scorch",
        "filename": "scorch",
        "count": "3"
    },
    "spe_rain": {
        "name": "Torrential Rain",
        "id": 11,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "rain",
        "filename": "rain",
        "count": "2"
    },
    "ntr_triss": {
        "name": "Triss Merigold",
        "id": 12,
        "deck": "neutral",
        "row": "close",
        "strength": "7",
        "ability": "hero",
        "filename": "triss",
        "count": "1"
    },
    "ntr_vesemir": {
        "name": "Vesemir",
        "id": 13,
        "deck": "neutral",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "vesemir",
        "count": "1"
    },
    "ntr_villen": {
        "name": "Villentretenmerth",
        "id": 14,
        "deck": "neutral",
        "row": "close",
        "strength": "7",
        "ability": "scorch_c",
        "filename": "villen",
        "count": "1"
    },
    "ntr_yennefer": {
        "name": "Yennefer of Vengerberg",
        "id": 15,
        "deck": "neutral",
        "row": "ranged",
        "strength": "7",
        "ability": "hero medic",
        "filename": "yennefer",
        "count": "1"
    },
    "ntr_zoltan": {
        "name": "Zoltan Chivay",
        "id": 16,
        "deck": "neutral",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "zoltan",
        "count": "1"
    },
    "ntr_olgierd": {
        "name": "Olgierd von Everec",
        "id": 17,
        "deck": "neutral",
        "row": "agile",
        "strength": "6",
        "ability": "morale",
        "filename": "olgierd",
        "count": "1"
    },
    "ntr_gaunter_odimm": {
        "name": "Gaunter O'Dimm",
        "id": 18,
        "deck": "neutral",
        "row": "siege",
        "strength": "2",
        "ability": "muster",
        "filename": "gaunter_odimm",
        "count": "1",
        "target": "ntr_gaunter_odimm"
    },
    "ntr_gaunter_odimm_darkness": {
        "name": "Gaunter O'Dimm - Darkness",
        "id": 19,
        "deck": "neutral",
        "row": "ranged",
        "strength": "4",
        "ability": "muster",
        "filename": "gaunter_odimm_darkness",
        "count": "3",
        "target": "ntr_gaunter_odimm"
    },
    "ntr_cow": {
        "name": "Cow",
        "id": 20,
        "deck": "neutral",
        "row": "ranged",
        "strength": "0",
        "ability": "avenger",
        "filename": "cow",
        "count": "1",
        "target": "ntr_chort"
    },
    "ntr_chort": {
        "name": "Bovine Defense Force",
        "id": 21,
        "deck": "neutral",
        "row": "close",
        "strength": "8",
        "ability": "",
        "filename": "chort",
        "count": "0"
    },
    "nr_foltest_silver": {
        "name": "Foltest - King of Temeria",
        "id": 22,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_king",
        "filename": "foltest_silver",
        "count": "1"
    },
    "nr_foltest_gold": {
        "name": "Foltest - Lord Commander of the North",
        "id": 23,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_lord",
        "filename": "foltest_gold",
        "count": "1"
    },
    "nr_foltest_copper": {
        "name": "Foltest - The Siegemaster",
        "id": 24,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_siegemaster",
        "filename": "foltest_copper",
        "count": "1"
    },
    "nr_foltest_bronze": {
        "name": "Foltest - The Steel-Forged",
        "id": 25,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_steelforged",
        "filename": "foltest_bronze",
        "count": "1"
    },
    "nr_foltest_son_of_medell": {
        "name": "Foltest - Son of Medell",
        "id": 26,
        "deck": "realms",
        "row": "leader",
        "strength": "",
        "ability": "foltest_son",
        "filename": "foltest_son_of_medell",
        "count": "1"
    },
    "nr_ballista": {
        "name": "Ballista",
        "id": 27,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "ballista",
        "count": "1"
    },
    "nr_blue_stripes_1": {
        "name": "Blue Stripes Commando",
        "id": 28,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_1",
        "count": "1",
        "target": "nr_blue_stripes"
    },
    "nr_blue_stripes_2": {
        "name": "Blue Stripes Commando",
        "id": 29,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_2",
        "count": "1",
        "target": "nr_blue_stripes"
    },
    "nr_blue_stripes_3": {
        "name": "Blue Stripes Commando",
        "id": 30,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "blue_stripes_3",
        "count": "1",
        "target": "nr_blue_stripes"
    },
    "nr_catapult_1": {
        "name": "Catapult",
        "id": 31,
        "deck": "realms",
        "row": "siege",
        "strength": "8",
        "ability": "bond",
        "filename": "catapult_1",
        "count": "1",
        "target": "nr_catapult"
    },
    "nr_catapult_2": {
        "name": "Catapult",
        "id": 32,
        "deck": "realms",
        "row": "siege",
        "strength": "8",
        "ability": "bond",
        "filename": "catapult_2",
        "count": "1",
        "target": "nr_catapult"
    },
    "nr_crinfrid_1": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 33,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_1",
        "count": "1",
        "target": "nr_crinfrid"
    },
    "nr_crinfrid_2": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 34,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_2",
        "count": "1",
        "target": "nr_crinfrid"
    },
    "nr_crinfrid_3": {
        "name": "Crinfrid Reavers Dragon Hunter",
        "id": 35,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "bond",
        "filename": "crinfrid_3",
        "count": "1",
        "target": "nr_crinfrid"
    },
    "nr_dethmold": {
        "name": "Dethmold",
        "id": 36,
        "deck": "realms",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "dethmold",
        "count": "1"
    },
    "nr_banner_nurse": {
        "name": "Dun Banner Medic",
        "id": 37,
        "deck": "realms",
        "row": "siege",
        "strength": "5",
        "ability": "medic",
        "filename": "banner_nurse",
        "count": "1"
    },
    "nr_esterad": {
        "name": "Esterad Thyssen",
        "id": 38,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "esterad",
        "count": "1"
    },
    "nr_natalis": {
        "name": "John Natalis",
        "id": 39,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "natalis",
        "count": "1"
    },
    "nr_kaedwen_siege": {
        "name": "Kaedweni Siege Expert",
        "id": 40,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege",
        "count": "1"
    },
    "nr_kaedwen_siege_1": {
        "name": "Kaedweni Siege Expert",
        "id": 41,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege_1",
        "count": "1"
    },
    "nr_kaedwen_siege_2": {
        "name": "Kaedweni Siege Expert",
        "id": 42,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "morale",
        "filename": "kaedwen_siege_2",
        "count": "1"
    },
    "nr_keira": {
        "name": "Keira Metz",
        "id": 43,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "keira",
        "count": "1"
    },
    "nr_philippa": {
        "name": "Philippa Eilhart",
        "id": 44,
        "deck": "realms",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "philippa",
        "count": "1"
    },
    "nr_poor_infantry_1": {
        "name": "Poor Fucking Infantry",
        "id": 45,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_1",
        "count": "1",
        "target": "nr_poor_infantry"
    },
    "nr_poor_infantry_2": {
        "name": "Poor Fucking Infantry",
        "id": 46,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_2",
        "count": "1",
        "target": "nr_poor_infantry"
    },
    "nr_poor_infantry_3": {
        "name": "Poor Fucking Infantry",
        "id": 47,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_3",
        "count": "1",
        "target": "nr_poor_infantry"
    },
    "nr_poor_infantry_4": {
        "name": "Poor Fucking Infantry",
        "id": 48,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "bond",
        "filename": "poor_infantry_4",
        "count": "1",
        "target": "nr_poor_infantry"
    },
    "nr_stennis": {
        "name": "Prince Stennis",
        "id": 49,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "spy",
        "filename": "stennis",
        "count": "1"
    },
    "nr_redania": {
        "name": "Redanian Foot Soldier",
        "id": 50,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "",
        "filename": "redania",
        "count": "1"
    },
    "nr_redania_1": {
        "name": "Redanian Foot Soldier",
        "id": 51,
        "deck": "realms",
        "row": "close",
        "strength": "1",
        "ability": "",
        "filename": "redania_1",
        "count": "1"
    },
    "nr_sheldon": {
        "name": "Sheldon Skaggs",
        "id": 52,
        "deck": "realms",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "sheldon",
        "count": "1"
    },
    "nr_siege_tower": {
        "name": "Siege Tower",
        "id": 53,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "siege_tower",
        "count": "1"
    },
    "nr_siegfried": {
        "name": "Siegfried of Denesle",
        "id": 54,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "siegfried",
        "count": "1"
    },
    "nr_dijkstra": {
        "name": "Sigismund Dijkstra",
        "id": 55,
        "deck": "realms",
        "row": "close",
        "strength": "4",
        "ability": "spy",
        "filename": "dijkstra",
        "count": "1"
    },
    "nr_sheala": {
        "name": "Síle de Tansarville",
        "id": 56,
        "deck": "realms",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "sheala",
        "count": "1"
    },
    "nr_thaler": {
        "name": "Thaler",
        "id": 57,
        "deck": "realms",
        "row": "siege",
        "strength": "1",
        "ability": "spy",
        "filename": "thaler",
        "count": "1"
    },
    "nr_sabrina": {
        "name": "Sabrina Glevissig",
        "id": 58,
        "deck": "realms",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "sabrina",
        "count": "1"
    },
    "nr_vernon": {
        "name": "Vernon Roche",
        "id": 59,
        "deck": "realms",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "vernon",
        "count": "1"
    },
    "nr_ves": {
        "name": "Ves",
        "id": 60,
        "deck": "realms",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "ves",
        "count": "1"
    },
    "nr_yarpen": {
        "name": "Yarpen Zigrin",
        "id": 61,
        "deck": "realms",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "yarpen",
        "count": "1"
    },
    "nr_trebuchet": {
        "name": "Trebuchet",
        "id": 62,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "trebuchet",
        "count": "1"
    },
    "nr_trebuchet_1": {
        "name": "Trebuchet",
        "id": 63,
        "deck": "realms",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "trebuchet_1",
        "count": "1"
    },
    "ne_emhyr_silver": {
        "name": "Emhyr var Emreis - His Imperial Majesty",
        "id": 64,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_imperial",
        "filename": "emhyr_silver",
        "count": "1"
    },
    "ne_emhyr_copper": {
        "name": "Emhyr var Emreis - Emperor of Nilfgaard",
        "id": 65,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_emperor",
        "filename": "emhyr_copper",
        "count": "1"
    },
    "ne_emhyr_bronze": {
        "name": "Emhyr var Emreis - the White Flame",
        "id": 66,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_whiteflame",
        "filename": "emhyr_bronze",
        "count": "1"
    },
    "ne_emhyr_gold": {
        "name": "Emhyr var Emreis - The Relentless",
        "id": 67,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_relentless",
        "filename": "emhyr_gold",
        "count": "1"
    },
    "ne_emhyr_invader_of_the_north": {
        "name": "Emhyr var Emreis - Invader of the North",
        "id": 68,
        "deck": "nilfgaard",
        "row": "leader",
        "strength": "",
        "ability": "emhyr_invader",
        "filename": "emhyr_invader_of_the_north",
        "count": "1"
    },
    "ne_albrich": {
        "name": "Albrich",
        "id": 69,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "albrich",
        "count": "1"
    },
    "ne_assire": {
        "name": "Assire var Anahid",
        "id": 70,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "assire",
        "count": "1"
    },
    "ne_black_archer": {
        "name": "Black Infantry Archer",
        "id": 71,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "",
        "filename": "black_archer",
        "count": "1"
    },
    "ne_black_archer_1": {
        "name": "Black Infantry Archer",
        "id": 72,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "",
        "filename": "black_archer_1",
        "count": "1"
    },
    "ne_cahir": {
        "name": "Cahir Mawr Dyffryn aep Ceallach",
        "id": 73,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "cahir",
        "count": "1"
    },
    "ne_cynthia": {
        "name": "Cynthia",
        "id": 74,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "cynthia",
        "count": "1"
    },
    "ne_archer_support": {
        "name": "Etolian Auxiliary Archers",
        "id": 75,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "1",
        "ability": "medic",
        "filename": "archer_support",
        "count": "1"
    },
    "ne_archer_support_1": {
        "name": "Etolian Auxiliary Archers",
        "id": 76,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "1",
        "ability": "medic",
        "filename": "archer_support_1",
        "count": "1"
    },
    "ne_fringilla": {
        "name": "Fringilla Vigo",
        "id": 77,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "fringilla",
        "count": "1"
    },
    "ne_heavy_zerri": {
        "name": "Heavy Zerrikanian Fire Scorpion",
        "id": 78,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "10",
        "ability": "",
        "filename": "heavy_zerri",
        "count": "1"
    },
    "ne_imperal_brigade_1": {
        "name": "Impera Brigade Guard",
        "id": 79,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_1",
        "count": "1",
        "target": "ne_imperal_brigade"
    },
    "ne_imperal_brigade_2": {
        "name": "Impera Brigade Guard",
        "id": 80,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_2",
        "count": "1",
        "target": "ne_imperal_brigade"
    },
    "ne_imperal_brigade_3": {
        "name": "Impera Brigade Guard",
        "id": 81,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_3",
        "count": "1",
        "target": "ne_imperal_brigade"
    },
    "ne_imperal_brigade_4": {
        "name": "Impera Brigade Guard",
        "id": 82,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "bond",
        "filename": "imperal_brigade_4",
        "count": "1",
        "target": "ne_imperal_brigade"
    },
    "ne_letho": {
        "name": "Letho of Gulet",
        "id": 83,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "letho",
        "count": "1"
    },
    "ne_menno": {
        "name": "Menno Coehoorn",
        "id": 84,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "10",
        "ability": "hero medic",
        "filename": "menno",
        "count": "1"
    },
    "ne_morteisen": {
        "name": "Morteisen",
        "id": 85,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "3",
        "ability": "",
        "filename": "morteisen",
        "count": "1"
    },
    "ne_moorvran": {
        "name": "Morvran Voorhis",
        "id": 86,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "10",
        "ability": "hero",
        "filename": "moorvran",
        "count": "1"
    },
    "ne_nauzicaa_1": {
        "name": "Nausicaa Cavalry Rider",
        "id": 87,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_1",
        "count": "1",
        "target": "ne_nauzicaa"
    },
    "ne_nauzicaa_2": {
        "name": "Nausicaa Cavalry Rider",
        "id": 88,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_2",
        "count": "1",
        "target": "ne_nauzicaa"
    },
    "ne_nauzicaa_3": {
        "name": "Nausicaa Cavalry Rider",
        "id": 89,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "bond",
        "filename": "nauzicaa_3",
        "count": "1",
        "target": "ne_nauzicaa"
    },
    "ne_puttkammer": {
        "name": "Puttkammer",
        "id": 90,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "3",
        "ability": "",
        "filename": "puttkammer",
        "count": "1"
    },
    "ne_rainfarn": {
        "name": "Rainfarn",
        "id": 91,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "rainfarn",
        "count": "1"
    },
    "ne_renuald": {
        "name": "Renuald aep Matsen",
        "id": 92,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "renuald",
        "count": "1"
    },
    "ne_rotten": {
        "name": "Rotten Mangonel",
        "id": 93,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "3",
        "ability": "",
        "filename": "rotten",
        "count": "1"
    },
    "ne_shilard": {
        "name": "Shilard Fitz-Oesterlen",
        "id": 94,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "7",
        "ability": "spy",
        "filename": "shilard",
        "count": "1"
    },
    "ne_siege_engineer": {
        "name": "Siege Engineer",
        "id": 95,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "siege_engineer",
        "count": "1"
    },
    "ne_siege_support": {
        "name": "Siege Technician",
        "id": 96,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "0",
        "ability": "medic",
        "filename": "siege_support",
        "count": "1"
    },
    "ne_stefan": {
        "name": "Stefan Skellen",
        "id": 97,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "9",
        "ability": "spy",
        "filename": "stefan",
        "count": "1"
    },
    "ne_sweers": {
        "name": "Sweers",
        "id": 98,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "sweers",
        "count": "1"
    },
    "ne_tibor": {
        "name": "Tibor Eggebracht",
        "id": 99,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "tibor",
        "count": "1"
    },
    "ne_vanhemar": {
        "name": "Vanhemar",
        "id": 100,
        "deck": "nilfgaard",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "vanhemar",
        "count": "1"
    },
    "ne_vattier": {
        "name": "Vattier de Rideaux",
        "id": 101,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "4",
        "ability": "spy",
        "filename": "vattier",
        "count": "1"
    },
    "ne_vreemde": {
        "name": "Vreemde",
        "id": 102,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "vreemde",
        "count": "1"
    },
    "ne_young_emissary_1": {
        "name": "Young Emissary",
        "id": 103,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "5",
        "ability": "bond",
        "filename": "young_emissary_1",
        "count": "1",
        "target": "ne_young_emissary"
    },
    "ne_young_emissary_2": {
        "name": "Young Emissary",
        "id": 104,
        "deck": "nilfgaard",
        "row": "close",
        "strength": "5",
        "ability": "bond",
        "filename": "young_emissary_2",
        "count": "1",
        "target": "ne_young_emissary"
    },
    "ne_zerri": {
        "name": "Zerrikanian Fire Scorpion",
        "id": 105,
        "deck": "nilfgaard",
        "row": "siege",
        "strength": "5",
        "ability": "",
        "filename": "zerri",
        "count": "1"
    },
    "mo_eredin_silver": {
        "name": "Eredin - Commander of the Red Riders",
        "id": 106,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_commander",
        "filename": "eredin_silver",
        "count": "1"
    },
    "mo_eredin_bronze": {
        "name": "Eredin - Bringer of Death",
        "id": 107,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_bringer_of_death",
        "filename": "eredin_bronze",
        "count": "1"
    },
    "mo_eredin_gold": {
        "name": "Eredin - Destroyer of Worlds",
        "id": 108,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_destroyer",
        "filename": "eredin_gold",
        "count": "1"
    },
    "mo_eredin_copper": {
        "name": "Eredin - King of the Wild Hunt",
        "id": 109,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_king",
        "filename": "eredin_copper",
        "count": "1"
    },
    "mo_eredin_the_treacherous": {
        "name": "Eredin Bréacc Glas - The Treacherous",
        "id": 110,
        "deck": "monsters",
        "row": "leader",
        "strength": "",
        "ability": "eredin_treacherous",
        "filename": "eredin_the_treacherous",
        "count": "1"
    },
    "mo_arachas": {
        "name": "Arachas ",
        "id": 111,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas",
        "count": "1",
        "target": "mo_arachas"
    },
    "mo_arachas_1": {
        "name": "Arachas ",
        "id": 112,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas_1",
        "count": "1",
        "target": "mo_arachas"
    },
    "mo_arachas_2": {
        "name": "Arachas ",
        "id": 113,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "arachas_2",
        "count": "1",
        "target": "mo_arachas"
    },
    "mo_arachas_behemoth": {
        "name": "Arachas- Behemoth",
        "id": 114,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "muster",
        "filename": "arachas_behemoth",
        "count": "1",
        "target": "mo_arachas"
    },
    "mo_poroniec": {
        "name": "Botchling",
        "id": 115,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "poroniec",
        "count": "1"
    },
    "mo_celaeno_harpy": {
        "name": "Celaeno Harpy",
        "id": 116,
        "deck": "monsters",
        "row": "agile",
        "strength": "2",
        "ability": "",
        "filename": "celaeno_harpy",
        "count": "1"
    },
    "mo_cockatrice": {
        "name": "Cockatrice",
        "id": 117,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "cockatrice",
        "count": "1"
    },
    "mo_witch_velen": {
        "name": "Crone - Brewess",
        "id": 118,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen",
        "count": "1",
        "target": "mo_witch_velen"
    },
    "mo_witch_velen_1": {
        "name": "Crone - Weavess",
        "id": 119,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen_1",
        "count": "1",
        "target": "mo_witch_velen"
    },
    "mo_witch_velen_2": {
        "name": "Crone - Whispess",
        "id": 120,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "muster",
        "filename": "witch_velen_2",
        "count": "1",
        "target": "mo_witch_velen"
    },
    "mo_draug": {
        "name": "Draug",
        "id": 121,
        "deck": "monsters",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "draug",
        "count": "1"
    },
    "mo_earth_elemental": {
        "name": "Earth Elemental",
        "id": 122,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "earth_elemental",
        "count": "1"
    },
    "mo_endrega": {
        "name": "Endrega",
        "id": 123,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "endrega",
        "count": "1"
    },
    "mo_fiend": {
        "name": "Fiend",
        "id": 124,
        "deck": "monsters",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "fiend",
        "count": "1"
    },
    "mo_fire_elemental": {
        "name": "Fire Elemental",
        "id": 125,
        "deck": "monsters",
        "row": "siege",
        "strength": "6",
        "ability": "",
        "filename": "fire_elemental",
        "count": "1"
    },
    "mo_fogling": {
        "name": "Foglet",
        "id": 126,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "",
        "filename": "fogling",
        "count": "1"
    },
    "mo_forktail": {
        "name": "Forktail",
        "id": 127,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "forktail",
        "count": "1"
    },
    "mo_frightener": {
        "name": "Frightener",
        "id": 128,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "frightener",
        "count": "1"
    },
    "mo_gargoyle": {
        "name": "Gargoyle",
        "id": 129,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "gargoyle",
        "count": "1"
    },
    "mo_ghoul": {
        "name": "Ghoul",
        "id": 130,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul",
        "count": "1",
        "target": "mo_ghoul"
    },
    "mo_ghoul_1": {
        "name": "Ghoul",
        "id": 131,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul_1",
        "count": "1",
        "target": "mo_ghoul"
    },
    "mo_ghoul_2": {
        "name": "Ghoul",
        "id": 132,
        "deck": "monsters",
        "row": "close",
        "strength": "1",
        "ability": "muster",
        "filename": "ghoul_2",
        "count": "1",
        "target": "mo_ghoul"
    },
    "mo_gravehag": {
        "name": "Grave Hag",
        "id": 133,
        "deck": "monsters",
        "row": "ranged",
        "strength": "5",
        "ability": "",
        "filename": "gravehag",
        "count": "1"
    },
    "mo_gryffin": {
        "name": "Griffin",
        "id": 134,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "gryffin",
        "count": "1"
    },
    "mo_harpy": {
        "name": "Harpy",
        "id": 135,
        "deck": "monsters",
        "row": "agile",
        "strength": "2",
        "ability": "",
        "filename": "harpy",
        "count": "1"
    },
    "mo_frost_giant": {
        "name": "Ice Giant",
        "id": 136,
        "deck": "monsters",
        "row": "siege",
        "strength": "5",
        "ability": "",
        "filename": "frost_giant",
        "count": "1"
    },
    "mo_imlerith": {
        "name": "Imlerith",
        "id": 137,
        "deck": "monsters",
        "row": "close",
        "strength": "10",
        "ability": "hero",
        "filename": "imlerith",
        "count": "1"
    },
    "mo_kayran": {
        "name": "Kayran",
        "id": 138,
        "deck": "monsters",
        "row": "agile",
        "strength": "8",
        "ability": "hero morale",
        "filename": "kayran",
        "count": "1"
    },
    "mo_leshen": {
        "name": "Leshen",
        "id": 139,
        "deck": "monsters",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "leshen",
        "count": "1"
    },
    "mo_nekker": {
        "name": "Nekker",
        "id": 140,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker",
        "count": "1",
        "target": "mo_nekker"
    },
    "mo_nekker_1": {
        "name": "Nekker",
        "id": 141,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker_1",
        "count": "1",
        "target": "mo_nekker"
    },
    "mo_nekker_2": {
        "name": "Nekker",
        "id": 142,
        "deck": "monsters",
        "row": "close",
        "strength": "2",
        "ability": "muster",
        "filename": "nekker_2",
        "count": "1",
        "target": "mo_nekker"
    },
    "mo_mighty_maiden": {
        "name": "Plague Maiden",
        "id": 143,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mighty_maiden",
        "count": "1"
    },
    "mo_bruxa": {
        "name": "Vampire - Bruxa",
        "id": 144,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "bruxa",
        "count": "1",
        "target": "mo_vampire"
    },
    "mo_ekkima": {
        "name": "Vampire - Ekimmara",
        "id": 145,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "ekkima",
        "count": "1",
        "target": "mo_vampire"
    },
    "mo_fleder": {
        "name": "Vampire - Fleder",
        "id": 146,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "fleder",
        "count": "1",
        "target": "mo_vampire"
    },
    "mo_garkain": {
        "name": "Vampire - Garkain",
        "id": 147,
        "deck": "monsters",
        "row": "close",
        "strength": "4",
        "ability": "muster",
        "filename": "garkain",
        "count": "1",
        "target": "mo_vampire"
    },
    "mo_katakan": {
        "name": "Vampire - Katakan",
        "id": 148,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "katakan",
        "count": "1",
        "target": "mo_vampire"
    },
    "mo_werewolf": {
        "name": "Werewolf",
        "id": 149,
        "deck": "monsters",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "werewolf",
        "count": "1"
    },
    "mo_wyvern": {
        "name": "Wyvern",
        "id": 150,
        "deck": "monsters",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "wyvern",
        "count": "1"
    },
    "mo_toad": {
        "name": "Toad",
        "id": 151,
        "deck": "monsters",
        "row": "ranged",
        "strength": "7",
        "ability": "scorch_r",
        "filename": "toad",
        "count": "1"
    },
    "sc_francesca_silver": {
        "name": "Francesca Findabair - Queen of Dol Blathanna",
        "id": 152,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_queen",
        "filename": "francesca_silver",
        "count": "1"
    },
    "sc_francesca_gold": {
        "name": "Francesca Findabair - the Beautiful",
        "id": 153,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_beautiful",
        "filename": "francesca_gold",
        "count": "1"
    },
    "sc_francesca_copper": {
        "name": "Francesca Findabair - Daisy of the Valley",
        "id": 154,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_daisy",
        "filename": "francesca_copper",
        "count": "1"
    },
    "sc_francesca_bronze": {
        "name": "Francesca Findabair - Pureblood Elf",
        "id": 155,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_pureblood",
        "filename": "francesca_bronze",
        "count": "1"
    },
    "sc_francesca_hope_of_the_aen_seidhe": {
        "name": "Francesca Findabair - Hope of the Aen Seidhe",
        "id": 156,
        "deck": "scoiatael",
        "row": "leader",
        "strength": "",
        "ability": "francesca_hope",
        "filename": "francesca_hope_of_the_aen_seidhe",
        "count": "1"
    },
    "sc_ciaran": {
        "name": "Ciaran aep Easnillien",
        "id": 157,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "3",
        "ability": "",
        "filename": "ciaran",
        "count": "1"
    },
    "sc_barclay": {
        "name": "Barclay Els",
        "id": 158,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "barclay",
        "count": "1"
    },
    "sc_dennis": {
        "name": "Dennis Cranmer",
        "id": 159,
        "deck": "scoiatael",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "dennis",
        "count": "1"
    },
    "sc_dol_archer": {
        "name": "Dol Blathanna Archer",
        "id": 160,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "dol_archer",
        "count": "1"
    },
    "sc_dol_infantry": {
        "name": "Dol Blathanna Scout",
        "id": 161,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry",
        "count": "1"
    },
    "sc_dol_infantry_1": {
        "name": "Dol Blathanna Scout",
        "id": 162,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry_1",
        "count": "1"
    },
    "sc_dol_infantry_2": {
        "name": "Dol Blathanna Scout",
        "id": 163,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "dol_infantry_2",
        "count": "1"
    },
    "sc_dwarf": {
        "name": "Dwarven Skirmisher",
        "id": 164,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf",
        "count": "1",
        "target": "sc_dwarf"
    },
    "sc_dwarf_1": {
        "name": "Dwarven Skirmisher",
        "id": 165,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf_1",
        "count": "1",
        "target": "sc_dwarf"
    },
    "sc_dwarf_2": {
        "name": "Dwarven Skirmisher",
        "id": 166,
        "deck": "scoiatael",
        "row": "close",
        "strength": "3",
        "ability": "muster",
        "filename": "dwarf_2",
        "count": "1",
        "target": "sc_dwarf"
    },
    "sc_eithne": {
        "name": "Eithné",
        "id": 167,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "eithne",
        "count": "1"
    },
    "sc_elf_skirmisher": {
        "name": "Elven Skirmisher",
        "id": 168,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher",
        "count": "1",
        "target": "sc_elf_skirmisher"
    },
    "sc_elf_skirmisher_1": {
        "name": "Elven Skirmisher",
        "id": 169,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher_1",
        "count": "1",
        "target": "sc_elf_skirmisher"
    },
    "sc_elf_skirmisher_2": {
        "name": "Elven Skirmisher",
        "id": 170,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "muster",
        "filename": "elf_skirmisher_2",
        "count": "1",
        "target": "sc_elf_skirmisher"
    },
    "sc_filavandrel": {
        "name": "Filavandrel aen Fidhail",
        "id": 171,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "filavandrel",
        "count": "1"
    },
    "sc_havekar_nurse": {
        "name": "Havekar Healer",
        "id": 172,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse",
        "count": "1"
    },
    "sc_havekar_nurse_1": {
        "name": "Havekar Healer",
        "id": 173,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse_1",
        "count": "1"
    },
    "sc_havekar_nurse_2": {
        "name": "Havekar Healer",
        "id": 174,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "0",
        "ability": "medic",
        "filename": "havekar_nurse_2",
        "count": "1"
    },
    "sc_havekar_support": {
        "name": "Havekar Smuggler",
        "id": 175,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support",
        "count": "1",
        "target": "sc_havekar_support"
    },
    "sc_havekar_support_1": {
        "name": "Havekar Smuggler",
        "id": 176,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support_1",
        "count": "1",
        "target": "sc_havekar_support"
    },
    "sc_havekar_support_2": {
        "name": "Havekar Smuggler",
        "id": 177,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "muster",
        "filename": "havekar_support_2",
        "count": "1",
        "target": "sc_havekar_support"
    },
    "sc_ida": {
        "name": "Ida Emean aep Sivney",
        "id": 178,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "ida",
        "count": "1"
    },
    "sc_iorveth": {
        "name": "Iorveth",
        "id": 179,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "iorveth",
        "count": "1"
    },
    "sc_isengrim": {
        "name": "Isengrim Faoiltiarna",
        "id": 180,
        "deck": "scoiatael",
        "row": "close",
        "strength": "10",
        "ability": "hero morale",
        "filename": "isengrim",
        "count": "1"
    },
    "sc_mahakam": {
        "name": "Mahakaman Defender",
        "id": 181,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam",
        "count": "1"
    },
    "sc_mahakam_1": {
        "name": "Mahakaman Defender",
        "id": 182,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_1",
        "count": "1"
    },
    "sc_mahakam_2": {
        "name": "Mahakaman Defender",
        "id": 183,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_2",
        "count": "1"
    },
    "sc_mahakam_3": {
        "name": "Mahakaman Defender",
        "id": 184,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_3",
        "count": "1"
    },
    "sc_mahakam_4": {
        "name": "Mahakaman Defender",
        "id": 185,
        "deck": "scoiatael",
        "row": "close",
        "strength": "5",
        "ability": "",
        "filename": "mahakam_4",
        "count": "1"
    },
    "sc_milva": {
        "name": "Milva",
        "id": 186,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "morale",
        "filename": "milva",
        "count": "1"
    },
    "sc_riordain": {
        "name": "Riordain",
        "id": 187,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "1",
        "ability": "",
        "filename": "riordain",
        "count": "1"
    },
    "sc_saskia": {
        "name": "Saesenthessis",
        "id": 188,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "saskia",
        "count": "1"
    },
    "sc_toruviel": {
        "name": "Toruviel",
        "id": 189,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "2",
        "ability": "",
        "filename": "toruviel",
        "count": "1"
    },
    "sc_vrihedd_cadet": {
        "name": "Vrihedd Brigade Recruit",
        "id": 190,
        "deck": "scoiatael",
        "row": "ranged",
        "strength": "4",
        "ability": "",
        "filename": "vrihedd_cadet",
        "count": "1"
    },
    "sc_vrihedd_brigade": {
        "name": "Vrihedd Brigade Veteran",
        "id": 191,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "5",
        "ability": "",
        "filename": "vrihedd_brigade",
        "count": "1"
    },
    "sc_vrihedd_brigade_1": {
        "name": "Vrihedd Brigade Veteran",
        "id": 192,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "5",
        "ability": "",
        "filename": "vrihedd_brigade_1",
        "count": "1"
    },
    "sc_yaevinn": {
        "name": "Yaevinn",
        "id": 193,
        "deck": "scoiatael",
        "row": "agile",
        "strength": "6",
        "ability": "",
        "filename": "yaevinn",
        "count": "1"
    },
    "sk_berserker": {
        "name": "Berserker",
        "id": 194,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "berserker",
        "filename": "berserker",
        "count": "1",
        "target": "sk_vildkaarl"
    },
    "sk_birna": {
        "name": "Birna Bran",
        "id": 195,
        "deck": "skellige",
        "row": "close",
        "strength": "2",
        "ability": "medic",
        "filename": "birna",
        "count": "1"
    },
    "sk_blueboy": {
        "name": "Blueboy Lugos",
        "id": 196,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "blueboy",
        "count": "1"
    },
    "sk_cerys": {
        "name": "Cerys",
        "id": 197,
        "deck": "skellige",
        "row": "close",
        "strength": "10",
        "ability": "hero muster",
        "filename": "cerys",
        "count": "1",
        "target": "sk_shield_maiden"
    },
    "sk_brokva_archer": {
        "name": "Clan Brokva Archer",
        "id": 198,
        "deck": "skellige",
        "row": "ranged",
        "strength": "6",
        "ability": "",
        "filename": "brokva_archer",
        "count": "2"
    },
    "sk_dimun_pirate": {
        "name": "Clan Dimun Pirate",
        "id": 199,
        "deck": "skellige",
        "row": "ranged",
        "strength": "6",
        "ability": "scorch",
        "filename": "dimun_pirate",
        "count": "1"
    },
    "sk_shield_maiden_1": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 200,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_1",
        "count": "1",
        "target": "sk_shield_maiden"
    },
    "sk_shield_maiden_2": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 201,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_2",
        "count": "1",
        "target": "sk_shield_maiden"
    },
    "sk_shield_maiden_3": {
        "name": "Cerys - Clan Drummond Shield Maiden",
        "id": 202,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "bond",
        "filename": "shield_maiden_3",
        "count": "1",
        "target": "sk_shield_maiden"
    },
    "sk_heymaey": {
        "name": "Clan Heymaey Skald",
        "id": 203,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "heymaey",
        "count": "1"
    },
    "sk_tordarroch": {
        "name": "Clan Tordarroch Armorsmith",
        "id": 204,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "tordarroch",
        "count": "1"
    },
    "sk_craite_warrior_1": {
        "name": "Clan an Craite Warrior",
        "id": 205,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_1",
        "count": "1",
        "target": "sk_craite_warrior"
    },
    "sk_craite_warrior_2": {
        "name": "Clan an Craite Warrior",
        "id": 206,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_2",
        "count": "1",
        "target": "sk_craite_warrior"
    },
    "sk_craite_warrior_3": {
        "name": "Clan an Craite Warrior",
        "id": 207,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "bond",
        "filename": "craite_warrior_3",
        "count": "1",
        "target": "sk_craite_warrior"
    },
    "sk_donar": {
        "name": "Donar an Hindar",
        "id": 208,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "donar",
        "count": "1"
    },
    "sk_draig": {
        "name": "Draig Bon-Dhu",
        "id": 209,
        "deck": "skellige",
        "row": "siege",
        "strength": "2",
        "ability": "horn",
        "filename": "draig",
        "count": "1"
    },
    "sk_ermion": {
        "name": "Ermion",
        "id": 210,
        "deck": "skellige",
        "row": "ranged",
        "strength": "8",
        "ability": "hero mardroeme",
        "filename": "ermion",
        "count": "1"
    },
    "sk_hemdall": {
        "name": "Hemdall",
        "id": 211,
        "deck": "skellige",
        "row": "close",
        "strength": "11",
        "ability": "hero",
        "filename": "hemdall",
        "count": "0"
    },
    "sk_hjalmar": {
        "name": "Hjalmar",
        "id": 212,
        "deck": "skellige",
        "row": "ranged",
        "strength": "10",
        "ability": "hero",
        "filename": "hjalmar",
        "count": "1"
    },
    "sk_holger": {
        "name": "Holger Blackhand",
        "id": 213,
        "deck": "skellige",
        "row": "siege",
        "strength": "4",
        "ability": "",
        "filename": "holger",
        "count": "1"
    },
    "sk_kambi": {
        "name": "Kambi",
        "id": 214,
        "deck": "skellige",
        "row": "close",
        "strength": "0",
        "ability": "avenger_kambi",
        "filename": "kambi",
        "count": "1",
        "target": "sk_hemdall"
    },
    "sk_light_longship": {
        "name": "Light Longship",
        "id": 215,
        "deck": "skellige",
        "row": "ranged",
        "strength": "4",
        "ability": "muster",
        "filename": "light_longship",
        "count": "3",
        "target": "sk_light_longship"
    },
    "sk_madmad_lugos": {
        "name": "Madman Lugos",
        "id": 216,
        "deck": "skellige",
        "row": "close",
        "strength": "6",
        "ability": "",
        "filename": "madmad_lugos",
        "count": "1"
    },
    "spe_mardroeme": {
        "name": "Mardroeme",
        "id": 217,
        "deck": "special",
        "row": "",
        "strength": "",
        "ability": "mardroeme",
        "filename": "mardroeme",
        "count": "3"
    },
    "sk_olaf": {
        "name": "Olaf",
        "id": 218,
        "deck": "skellige",
        "row": "agile",
        "strength": "12",
        "ability": "morale",
        "filename": "olaf",
        "count": "1"
    },
    "spe_storm": {
        "name": "Skellige Storm",
        "id": 219,
        "deck": "weather",
        "row": "",
        "strength": "",
        "ability": "rain fog",
        "filename": "storm",
        "count": "3"
    },
    "sk_svanrige": {
        "name": "Svanrige",
        "id": 220,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "svanrige",
        "count": "1"
    },
    "sk_vildkaarl": {
        "name": "Transformed Vildkaarl",
        "id": 221,
        "deck": "skellige",
        "row": "close",
        "strength": "14",
        "ability": "morale",
        "filename": "vildkaarl",
        "count": "0"
    },
    "sk_young_vildkaarl": {
        "name": "Transformed Young Vildkaarl",
        "id": 222,
        "deck": "skellige",
        "row": "ranged",
        "strength": "8",
        "ability": "bond",
        "filename": "young_vildkaarl",
        "count": "0",
        "target": "sk_young_vildkaarl"
    },
    "sk_udalryk": {
        "name": "Udalryk",
        "id": 223,
        "deck": "skellige",
        "row": "close",
        "strength": "4",
        "ability": "",
        "filename": "udalryk",
        "count": "1"
    },
    "sk_war_longship_1": {
        "name": "War Longship",
        "id": 224,
        "deck": "skellige",
        "row": "siege",
        "strength": "6",
        "ability": "bond",
        "filename": "war_longship_1",
        "count": "1",
        "target": "sk_war_longship"
    },
    "sk_war_longship_2": {
        "name": "War Longship",
        "id": 225,
        "deck": "skellige",
        "row": "siege",
        "strength": "6",
        "ability": "bond",
        "filename": "war_longship_2",
        "count": "1",
        "target": "sk_war_longship"
    },
    "sk_young_berserker": {
        "name": "Young Berserker",
        "id": 226,
        "deck": "skellige",
        "row": "ranged",
        "strength": "2",
        "ability": "berserker",
        "filename": "young_berserker",
        "count": "3",
        "target": "sk_young_vildkaarl"
    },
    "sk_crach_an_craite": {
        "name": "Crach an Craite",
        "id": 227,
        "deck": "skellige",
        "row": "leader",
        "strength": "",
        "ability": "crach_an_craite",
        "filename": "crach_an_craite",
        "count": "0"
    },
    "sk_king_bran": {
        "name": "King Bran",
        "id": 228,
        "deck": "skellige",
        "row": "leader",
        "strength": "",
        "ability": "king_bran",
        "filename": "king_bran",
        "count": "0"
    },
    "sc_schirru": {
        "name": "Schirru",
        "id": 229,
        "deck": "scoiatael",
        "row": "siege",
        "strength": "8",
        "ability": "scorch_s",
        "filename": "schirru",
        "count": "1"
    }
};
