let default_decks = [
    {
        "title": "Default Northern Realms Deck 1",
        "description": "TBD",
        "leader": "nr_foltest_siegemaster",
        "faction": "realms",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_frost", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["nr_esterad", 1],
            ["nr_natalis", 1],
            ["nr_philippa", 1],
            ["nr_vernon", 1],
            ["nr_catapult_1", 1],
            ["nr_catapult_2", 1],
            ["ntr_triss", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["nr_ballista", 1],
            ["ntr_olgierd", 1],
            ["nr_siege_tower", 1],
            ["nr_trebuchet", 1],
            ["nr_trebuchet_1", 1],
            ["nr_crinfrid_1", 1],
            ["nr_crinfrid_2", 1],
            ["nr_crinfrid_3", 1],
            ["nr_banner_nurse", 1],
            ["nr_stennis", 1],
            ["nr_blue_stripes_1", 1],
            ["nr_blue_stripes_2", 1],
            ["nr_blue_stripes_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["nr_dijkstra", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["nr_thaler", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Northern Realms Deck 2",
        "description": "TBD",
        "leader": "nr_foltest_siegemaster",
        "faction": "realms",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["nr_esterad", 1],
            ["nr_natalis", 1],
            ["nr_philippa", 1],
            ["nr_vernon", 1],
            ["nr_catapult_1", 1],
            ["nr_catapult_2", 1],
            ["ntr_triss", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["nr_ballista", 1],
            ["ntr_olgierd", 1],
            ["nr_siege_tower", 1],
            ["nr_trebuchet", 1],
            ["nr_trebuchet_1", 1],
            ["nr_crinfrid_1", 1],
            ["nr_crinfrid_2", 1],
            ["nr_crinfrid_3", 1],
            ["nr_banner_nurse", 1],
            ["nr_stennis", 1],
            ["nr_blue_stripes_1", 1],
            ["nr_blue_stripes_2", 1],
            ["nr_blue_stripes_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["nr_dijkstra", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["nr_thaler", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Nilfgaard Deck 1",
        "description": "TBD",
        "leader": "ne_emhyr_relentless",
        "faction": "nilfgaard",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["ne_black_archer", 1],
            ["ne_black_archer_1", 1],
            ["ne_heavy_zerri", 1],
            ["ne_menno", 1],
            ["ne_moorvran", 1],
            ["ne_stefan", 1],
            ["ne_shilard", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["ntr_olgierd", 1],
            ["ne_young_emissary_1", 1],
            ["ne_young_emissary_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["ne_vattier", 1],
            ["ne_impera_brigade_1", 1],
            ["ne_impera_brigade_2", 1],
            ["ne_impera_brigade_3", 1],
            ["ne_impera_brigade_4", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["ne_archer_support", 1],
            ["ne_archer_support_1", 1],
            ["ntr_mysterious_elf", 1],
            ["ne_siege_support", 1]
        ]
    },
    {
        "title": "Default Nilfgaard Deck 2",
        "description": "TBD",
        "leader": "ne_emhyr_whiteflame",
        "faction": "nilfgaard",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 2],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["ne_black_archer", 1],
            ["ne_black_archer_1", 1],
            ["ne_heavy_zerri", 1],
            ["ne_menno", 1],
            ["ne_moorvran", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["ne_assire", 1],
            ["ne_cahir", 1],
            ["ne_fringilla", 1],
            ["ntr_olgierd", 1],
            ["ntr_vesemir", 1],
            ["ne_young_emissary_1", 1],
            ["ne_young_emissary_2", 1],
            ["ne_vattier", 1],
            ["ne_impera_brigade_1", 1],
            ["ne_impera_brigade_2", 1],
            ["ne_impera_brigade_3", 1],
            ["ne_impera_brigade_4", 1],
            ["ntr_dandelion", 1],
            ["ne_archer_support", 1],
            ["ne_archer_support_1", 1],
            ["ntr_cow", 1],
            ["ntr_mysterious_elf", 1],
            ["ne_siege_support", 1]
        ]
    },
    {
        "title": "Default Monster Deck 1",
        "description": "TBD",
        "leader": "mo_eredin_commander",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["mo_imlerith", 1],
            ["mo_kayran", 1],
            ["mo_toad", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["ntr_olgierd", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_botchling", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Monster Deck 2",
        "description": "TBD",
        "leader": "mo_eredin_bringer_of_death",
        "faction": "monsters",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 3],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["mo_kayran", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["ntr_olgierd", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Scoia'Tael Deck 1",
        "description": "TBD",
        "leader": "sc_francesca_daisy",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sc_isengrim", 1],
            ["sc_milva", 1],
            ["sc_schirru", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sc_dol_infantry", 1],
            ["ntr_olgierd", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["sc_ciaran", 1],
            ["sc_dwarf", 1],
            ["sc_dwarf_1", 1],
            ["sc_dwarf_2", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Scoia'Tael Deck 2",
        "description": "TBD",
        "leader": "sc_francesca_hope_of_the_aen_seidhe",
        "faction": "scoiatael",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sc_isengrim", 1],
            ["sc_milva", 1],
            ["sc_schirru", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sc_dol_infantry", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_filavandrel", 1],
            ["ntr_olgierd", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["ntr_cow", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Skellige Deck 1",
        "description": "TBD",
        "leader": "sk_crach_an_craite",
        "faction": "skellige",
        "cards": [
            ["spe_horn", 1],
            ["spe_mardroeme", 1],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_storm", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sk_olaf", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sk_craite_warrior_1", 1],
            ["sk_craite_warrior_2", 1],
            ["sk_craite_warrior_3", 1],
            ["sk_dimun_pirate", 1],
            ["ntr_olgierd", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship", 3],
            ["sk_birna", 1],
            ["ntr_dandelion", 1],
            ["sk_young_berserker", 3],
            ["sk_kambi", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Skellige Deck 2",
        "description": "TBD",
        "leader": "sk_crach_an_craite",
        "faction": "skellige",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sk_olaf", 1],
            ["sk_cerys", 1],
            ["ntr_villen", 1],
            ["sk_craite_warrior_1", 1],
            ["sk_craite_warrior_2", 1],
            ["sk_craite_warrior_3", 1],
            ["sk_dimun_pirate", 1],
            ["ntr_olgierd", 1],
            ["sk_war_longship_1", 1],
            ["sk_war_longship_2", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["sk_light_longship", 3],
            ["sk_birna", 1],
            ["ntr_mysterious_elf", 1]
        ]
    }
];

/*
 * Custom decks with custom cards
 */

var custom_decks = [
    {
        "title": "Northern Realms - Temeria",
        "description": "Northern Realms deck focusing on Temerian cards - Playstyle: Tight Bond, Spy",
        "leader": "nr_foltest_lord",
        "faction": "realms",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_fog", 1],
            ["spe_scorch", 1],
            ["nr_esterad", 1],
            ["nr_natalis", 1],
            ["nr_philippa", 1],
            ["nr_vernon", 1],
            ["nr_ballista", 1],
            ["nr_siege_tower", 1],
            ["nr_trebuchet_1", 1],
            ["nr_crinfrid_1", 1],
            ["nr_crinfrid_2", 1],
            ["nr_crinfrid_3", 1],
            ["nr_blue_stripes_1", 1],
            ["nr_blue_stripes_2", 1],
            ["nr_blue_stripes_3", 1],
            ["nr_dijkstra", 1],
            ["nr_thaler", 1],
            ["nr_tridam_infantry", 1],
            ["nr_temerian_soldier_1", 1],
            ["nr_temerian_soldier_2", 1],
            ["nr_temerian_soldier_3", 1],
            ["nr_stripes_scout", 1],
            ["nr_temerian_drummer", 1],
            ["nr_foltest_pride", 1],
            ["nr_reaver_scout", 1]
        ]
    },
    {
        "title": "Northern Realms - Kaedwen & Aedirn",
        "description": "Northern Realms deck focusing on Kaedwen and Aedirn cards - Playstyle: Siege units, Morale boost, Tight Bond",
        "leader": "nr_foltest_siegemaster",
        "faction": "realms",
        "cards": [
            ["spe_horn", 2],
            ["spe_decoy", 2],
            ["spe_fog", 1],
            ["spe_clear", 1],
            ["spe_scorch", 2],
            ["nr_stennis", 1],
            ["nr_vandergrift", 1],
            ["nr_kaedweni_siege_support_1", 1],
            ["nr_kaedweni_siege_support_2", 1],
            ["nr_catapult_1", 1],
            ["nr_catapult_2", 1],
            ["nr_henselt", 1],
            ["nr_kaedweni_reinforcement", 1],
            ["nr_reinforced_ballista_1", 1],
            ["nr_reinforced_ballista_2", 1],
            ["nr_reinforced_trebuchet_1", 1],
            ["nr_reinforced_trebuchet_2", 1],
            ["nr_banner_nurse", 1],
            ["nr_ban_ard_tutor", 1],
            ["nr_demavend", 1],
            ["nr_kaedweni_knight", 1],
            ["nr_dun_banner_heavy_cavalry_1", 1],
            ["nr_dun_banner_heavy_cavalry_2", 1],
            ["nr_odrin", 1],
            ["nr_seltkirk", 1],
            ["nr_kaedweni_sergeant", 1],
            ["nr_dethmold", 1]
        ]
    },
    {
        "title": "Northern Realms - Cintra & Neighbours",
        "description": "Northern Realms deck focusing on Cintra and neighbour minor realsms - Playstyle: Summon Avenger, Slaughter of Cintra, Muster",
        "leader": "nr_queen_calanthe",
        "faction": "realms",
        "cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["spe_storm", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["spe_slaughther_cintra_1", 1],
            ["spe_slaughther_cintra_2", 1],
            ["nr_viraxas", 1],
            ["nr_kerack_fleet_marine_2", 1],
            ["nr_kerack_fleet_frigate", 1],
            ["nr_kerack_fleet_marine_1", 1],
            ["nr_vissegerd", 1],
            ["nr_cintrian_royal_guard", 1],
            ["nr_eist_tuirseach", 1],
            ["nr_skellige_fleet_1", 1],
            ["nr_skellige_fleet_2", 1],
            ["nr_skellige_fleet_3", 1],
            ["nr_cintrian_knight", 1],
            ["nr_roegner", 1],
            ["nr_pavetta", 1],
            ["nr_kistrin_verden", 1],
            ["nr_sha", 1],
            ["nr_kraken", 1],
            ["nr_egmund", 1],
            ["nr_eylembert_tigg", 1],
            ["nr_young_ciri", 1],
            ["ntr_ciri", 1],
            ["nr_cintrian_peasants", 1],
            ["nr_windhalm", 1]
        ]
    },
    {
        "title": "Nilfgaard Empire - Army",
        "description": "Nilfgaard Empire deck focusing on army cards - Playstyle: Tight Bond, Heroes, Medic, Horn",
        "leader": "ne_emhyr_relentless",
        "faction": "nilfgaard",
        "cards": [
            ["spe_fog", 1],
            ["spe_decoy", 2],
            ["spe_rain", 1],
            ["spe_clear", 2],
            ["spe_scorch", 2],
            ["ne_vicovaro_medic", 1],
            ["ne_nauzicaa_1", 1],
            ["ne_nauzicaa_2", 1],
            ["ne_nauzicaa_3", 1],
            ["ne_shilard", 1],
            ["ne_alba_pikeman_1", 1],
            ["ne_archer_support", 1],
            ["ne_archer_support_1", 1],
            ["ne_nausicaa_brigade", 1],
            ["ne_imperial_golem", 1],
            ["ne_daerlan_soldier", 1],
            ["ne_hefty_helge", 1],
            ["ne_heavy_zerri", 1],
            ["ne_slave_infantry_1", 1],
            ["ne_slave_infantry_2", 1],
            ["ne_magne_division", 1],
            ["ne_emissary", 1],
            ["ne_alba_spearman", 1],
            ["ne_standard_bearer", 1],
            ["ne_black_archer", 1],
            ["ne_black_archer_1", 1],
            ["ne_deithwen_arbalest", 1],
            ["ne_guardian", 1],
            ["ne_siege_support", 1],
            ["ne_nausicaa_standard_bearer", 1],
            ["ne_knight", 1],
            ["ne_alba_armored_cavalry", 1],
            ["ne_menno", 1]
            
        ]
    },
    {
        "title": "Nilfgaard Empire - Nobility",
        "description": "Nilfgaard Empire deck focusing on the nobility & aristocrats - Playstyle: Tight Bond, Spy",
        "leader": "ne_emhyr_emperor",
        "faction": "nilfgaard",
        "cards": [
            ["spe_fog", 2],
            ["spe_horn", 2],
            ["spe_clear", 2],
            ["spe_scorch", 1],
            ["ne_impera_brigade_1", 1],
            ["ne_impera_brigade_2", 1],
            ["ne_impera_brigade_3", 1],
            ["ne_impera_brigade_4", 1],
            ["ne_impera_brigade_5", 1],
            ["ne_jan_calveit", 1],
            ["ne_vattier", 1],
            ["ne_letho", 1],
            ["ne_bribery", 1],
            ["ne_epidemic", 1],
            ["ne_rot_tosser", 1],
            ["ne_moorvran", 1],
            ["ne_fringilla", 1],
            ["ne_tibor", 1],
            ["ne_young_emissary_1", 1],
            ["ne_young_emissary_2", 1],
            ["ne_cahir", 1],
            ["ne_stefan", 1],
            ["ne_joachim_de_wett", 1],
            ["ne_ardal_aep_dahy", 1],
            ["ne_cantarella", 1],
            ["ne_assire", 1],
            ["ne_treason", 1]
        ]
    },
    {
        "title": "Monsters - Wild Hunt & Giants",
        "description": "Monsters deck focusing on the wild hunt and giants - Playstyle: Muster, Tall units",
        "leader": "mo_eredin_bringer_of_death",
        "faction": "monsters",
        "cards": [
            ["spe_fog", 2],
            ["spe_decoy", 2],
            ["spe_clear", 1],
            ["spe_scorch", 2],
            ["spe_horn", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["mo_golem", 1],
            ["mo_geels", 1],
            ["mo_ifrit_1", 1],
            ["mo_ifrit_2", 1],
            ["mo_fire_elemental", 1],
            ["mo_wild_hunt_rider_1", 1],
            ["mo_wild_hunt_rider_2", 1],
            ["mo_wild_hunt_rider_3", 1],
            ["mo_nithral", 1],
            ["mo_therazane", 1],
            ["mo_naglfar", 1],
            ["mo_caranthir", 1],
            ["mo_jotunn", 1],
            ["mo_frost_giant", 1],
            ["mo_imlerith", 1],
            ["mo_old_speartip", 1],
            ["mo_navigator", 1],
            ["mo_cyclops", 1],
            ["mo_ice_troll", 1],
            ["mo_earth_elemental", 1]
        ]
    },
    {
        "title": "Monsters - Beasts & Creatures",
        "description": "Monsters deck focusing on the multitude of beasts and creatures - Playstyle: Muster",
        "leader": "mo_eredin_commander",
        "faction": "monsters",
        "cards": [
            ["spe_rain", 2],
            ["spe_decoy", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["spe_horn", 2],
            ["mo_morvudd", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["mo_ekkima", 1],
            ["mo_bruxa", 1],
            ["mo_katakan", 1],
            ["mo_ghoul", 1],
            ["mo_ghoul_1", 1],
            ["mo_ghoul_2", 1],
            ["mo_kayran", 1],
            ["mo_lamia_1", 1],
            ["mo_lamia_2", 1],
            ["mo_lamia_3", 1],
            ["mo_glustyworp", 1],
            ["mo_alghoul", 1],
            ["mo_archgriffin", 1],
            ["mo_alp", 1],
            ["mo_toad", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_armoured_arachas", 1],
            ["mo_leshen", 1],
            ["mo_dragon_fyresdal", 1],
            ["mo_manticore", 1],
            ["mo_manticore_venom", 1]
        ]
    },
    {
        "title": "Scoia'Tael - Commandos",
        "description": "Scoia'Tael deck focusing on the commandos units - Playstyle: Muster, Medic",
        "leader": "sc_francesca_daisy",
        "faction": "scoiatael",
        "cards": [
            ["spe_rain", 1],
            ["spe_decoy", 2],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["spe_horn", 2],
            ["sc_elven_mercenary_1", 1],
            ["sc_elven_mercenary_2", 1],
            ["sc_vrihedd_sapper", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_1", 1],
            ["sc_havekar_nurse_2", 1],
            ["sc_iorveth", 1],
            ["sc_vrihedd_dragoon_1", 1],
            ["sc_vrihedd_dragoon_2", 1],
            ["sc_vrihedd_dragoon_3", 1],
            ["sc_isengrim", 1],
            ["sc_vrihedd_brigade", 1],
            ["sc_vrihedd_brigade_1", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["sc_aelirenn", 1],
            ["sc_saesenthessis_saskia", 1],
            ["sc_saesenthessis_dragon", 1],
            ["sc_neophyte", 1],
            ["sc_yaevinn", 1],
            ["sc_vrihedd_officer", 1]
        ]
    },
    {
        "title": "Scoia'Tael - Independant Realms",
        "description": "Scoia'Tael deck focusing on the non-humans realms such as Dol Blathanna, Mahakam or Brokilon - Playstyle: Muster, Morale",
        "leader": "sc_francesca_beautiful",
        "faction": "scoiatael",
        "cards": [
            ["spe_rain", 1],
            ["spe_frost", 1],
            ["spe_decoy", 1],
            ["spe_clear", 1],
            ["spe_scorch", 2],
            ["spe_horn", 1],
            ["sc_eithne", 1],
            ["sc_barclay", 1],
            ["sc_dol_blathanna_sentry", 1],
            ["sc_milva", 1],
            ["sc_dryads_1", 1],
            ["sc_dryads_2", 1],
            ["sc_dryads_3", 1],
            ["sc_dryads_4", 1],
            ["sc_brouver_hoog", 1],
            ["sc_dol_blathanna_guard_1", 1],
            ["sc_dol_blathanna_guard_2", 1],
            ["sc_dol_blathanna_guard_3", 1],
            ["sc_aglais", 1],
            ["sc_elven_deadeye", 1],
            ["sc_morenn", 1],
            ["sc_mahakam_pyrotechnician", 1],
            ["sc_mahakam_guard_1", 1],
            ["sc_mahakam_guard_2", 1],
            ["sc_mahakam_ale", 1],
            ["sc_yannick_brass", 1],
            ["sc_dol_blathanna_trapper", 1],
            ["sc_gabor_zigrin", 1]
        ]
    },
    {
        "title": "Skellige - Ard Skellig & Svalblod",
        "description": "Skellige deck focusing on the cards from Ard Skellige and the Svalblod cult - Playstyle: Berserker, Muster, Tight Bond",
        "leader": "sk_crach_an_craite",
        "faction": "skellige",
        "cards": [
            ["spe_storm", 2],
            ["spe_mardroeme", 3],
            ["spe_decoy", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["spe_horn", 1],
            ["sk_blueboy", 1],
            ["sk_hjalmar", 1],
            ["sk_vabjorn", 1],
            ["sk_young_berserker", 3],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_an_craite_greatsword", 1],
            ["sk_drummond_warmonger", 1],
            ["sk_madman_lugos", 1],
            ["sk_harald_cripple", 1],
            ["sk_craite_warrior_1", 1],
            ["sk_craite_warrior_2", 1],
            ["sk_craite_warrior_3", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["sk_svalblod_fanatic", 1],
            ["sk_an_craite_raiders", 1],
            ["sk_berserker", 1],
            ["sk_svalblod", 1],
            ["sk_morkvarg", 1]
        ]
    },
    {
        "title": "Skellige - Small islands",
        "description": "Skellige deck focusing on the cards from the other islands - Playstyle: Muster, Tight Bond, Medic",
        "leader": "sk_king_bran",
        "faction": "skellige",
        "cards": [
            ["spe_frost", 3],
            ["spe_decoy", 2],
            ["spe_scorch", 2],
            ["spe_horn", 2],
            ["sk_olaf", 1],
            ["sk_birna", 1],
            ["sk_war_longship_1", 1],
            ["sk_war_longship_2", 1],
            ["sk_war_longship_3", 1],
            ["sk_dimun_pirate_captain", 1],
            ["sk_vigi_loon", 1],
            ["sk_light_longship", 3],
            ["sk_brokva_archer", 2],
            ["sk_tuirseach_warrior_1", 1],
            ["sk_tuirseach_warrior_2", 1],
            ["sk_heymaey_flaminica", 1],
            ["sk_eist_tuirseach", 1],
            ["sk_kambi", 1],
            ["sk_arnjolf", 1],
            ["sk_otkell", 1],
            ["sk_dagur", 1],
            ["sk_sigrdrifa", 1],
            ["sk_dimun_pirate", 1],
            ["sk_jutta", 1]
        ]
    },
    {
        "title": "Witcher Universe - Fighters & Mages",
        "description": "Witcher Universe deck focusing on the famous fighters and mages - Playstyle: Muster, Medic",
        "leader": "wu_vilgefortz_magician_kovir",
        "faction": "witcher_universe",
        "cards": [
            ["spe_frost", 1],
            ["spe_fog", 1],
            ["spe_decoy", 1],
            ["spe_clear", 1],
            ["spe_scorch", 1],
            ["spe_horn", 1],
            ["wu_tissaia", 1],
            ["wu_rats_giselher", 1],
            ["wu_rats_asse", 1],
            ["wu_rats_iskra", 1],
            ["wu_rats_kayleigh", 1],
            ["wu_rats_mistle", 1],
            ["wu_rats_reef", 1],
            ["wu_ralf_blunden", 1],
            ["wu_bomb_heaver", 1],
            ["wu_gascon_light_cavalry", 1],
            ["wu_gascon_slinger", 1],
            ["wu_gascon_infiltrator", 1],
            ["wu_gascon", 1],
            ["wu_dorregaray", 1],
            ["wu_ortolan", 1],
            ["wu_coral", 1],
            ["wu_leo_bonhart", 1],
            ["wu_azar_javed", 1],
            ["wu_strays_spalla", 1],
            ["wu_gerhart_aelle", 1],
            ["wu_lydia_bredevoort", 1],
            ["wu_dana_meadbh", 1],
            ["wu_rience", 1],
            ["wu_visenna", 1],
            ["wu_operator",1]
        ]
    },
    {
        "title": "Witcher Universe - Witchers",
        "description": "Witcher Universe deck focusing on witcher schools - Playstyle: Witcher Schools, Resilience, Scorch",
        "leader": "wu_cosimo_malaspina",
        "faction": "witcher_universe",
        "cards": [
            ["wu_coen", 1],
            ["wu_stygga_castle", 1],
            ["wu_vesemir", 1],
            ["wu_haern_caduch", 1],
            ["wu_ivo_belhaven", 1],
            ["wu_lambert", 1],
            ["wu_keldar", 1],
            ["wu_ivar", 1],
            ["wu_gorthur_gvaed", 1],
            ["wu_kaer_morhen", 1],
            ["wu_kaer_seren", 1],
            ["wu_gezras", 1],
            ["wu_geralt_1", 1],
            ["wu_gaetan", 1],
            ["wu_brehen", 1],
            ["wu_gerd", 1],
            ["wu_warrit", 1],
            ["wu_erland", 1],
            ["wu_arnaghad", 1],
            ["wu_letho", 1],
            ["wu_eskel", 1],
            ["wu_kolgrim", 1],
            ["wu_swallow_potion", 1]
        ]
    }
];

/*
 * 
 */

var premade_deck = default_decks;
premade_deck = custom_decks.concat(premade_deck);