let premade_deck = [
    {
        "title": "Default Northern Realms Deck 1",
        "description": "TBD",
        "leader": "nr_foltest_copper",
        "faction": "realms",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_frost", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["nr_esterad", 1],
            ["nr_natalis", 1],
            ["nr_philippa", 1],
            ["nr_vernon", 1],
            ["nr_catapult_1", 1],
            ["nr_catapult_2", 1],
            ["ntr_triss", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["nr_ballista", 1],
            ["ntr_olgierd", 1],
            ["nr_siege_tower", 1],
            ["nr_trebuchet", 1],
            ["nr_trebuchet_1", 1],
            ["nr_crinfrid_1", 1],
            ["nr_crinfrid_2", 1],
            ["nr_crinfrid_3", 1],
            ["nr_banner_nurse", 1],
            ["nr_stennis", 1],
            ["nr_blue_stripes_1", 1],
            ["nr_blue_stripes_2", 1],
            ["nr_blue_stripes_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["nr_dijkstra", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["nr_thaler", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Northern Realms Deck 2",
        "description": "TBD",
        "leader": "nr_foltest_copper",
        "faction": "realms",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["nr_esterad", 1],
            ["nr_natalis", 1],
            ["nr_philippa", 1],
            ["nr_vernon", 1],
            ["nr_catapult_1", 1],
            ["nr_catapult_2", 1],
            ["ntr_triss", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["nr_ballista", 1],
            ["ntr_olgierd", 1],
            ["nr_siege_tower", 1],
            ["nr_trebuchet", 1],
            ["nr_trebuchet_1", 1],
            ["nr_crinfrid_1", 1],
            ["nr_crinfrid_2", 1],
            ["nr_crinfrid_3", 1],
            ["nr_banner_nurse", 1],
            ["nr_stennis", 1],
            ["nr_blue_stripes_1", 1],
            ["nr_blue_stripes_2", 1],
            ["nr_blue_stripes_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["nr_dijkstra", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["nr_thaler", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Nilfgaard Deck 1",
        "description": "TBD",
        "leader": "ne_emhyr_gold",
        "faction": "nilfgaard",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["ne_black_archer", 1],
            ["ne_black_archer_1", 1],
            ["ne_heavy_zerri", 1],
            ["ne_menno", 1],
            ["ne_moorvran", 1],
            ["ne_stefan", 1],
            ["ne_shilard", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["ntr_olgierd", 1],
            ["ne_young_emissary_1", 1],
            ["ne_young_emissary_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["ne_vattier", 1],
            ["ne_imperal_brigade_1", 1],
            ["ne_imperal_brigade_2", 1],
            ["ne_imperal_brigade_3", 1],
            ["ne_imperal_brigade_4", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["ne_archer_support", 1],
            ["ne_archer_support_1", 1],
            ["ntr_mysterious_elf", 1],
            ["ne_siege_support", 1]
        ]
    },
    {
        "title": "Default Nilfgaard Deck 2",
        "description": "TBD",
        "leader": "ne_emhyr_bronze",
        "faction": "nilfgaard",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 2],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["ne_black_archer", 1],
            ["ne_black_archer_1", 1],
            ["ne_heavy_zerri", 1],
            ["ne_menno", 1],
            ["ne_moorvran", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["ne_assire", 1],
            ["ne_cahir", 1],
            ["ne_fringilla", 1],
            ["ntr_olgierd", 1],
            ["ntr_vesemir", 1],
            ["ne_young_emissary_1", 1],
            ["ne_young_emissary_2", 1],
            ["ne_vattier", 1],
            ["ne_imperal_brigade_1", 1],
            ["ne_imperal_brigade_2", 1],
            ["ne_imperal_brigade_3", 1],
            ["ne_imperal_brigade_4", 1],
            ["ntr_dandelion", 1],
            ["ne_archer_support", 1],
            ["ne_archer_support_1", 1],
            ["ntr_cow", 1],
            ["ntr_mysterious_elf", 1],
            ["ne_siege_support", 1]
        ]
    },
    {
        "title": "Default Monster Deck 1",
        "description": "TBD",
        "leader": "mo_eredin_silver",
        "faction": "monsters",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["mo_imlerith", 1],
            ["mo_kayran", 1],
            ["mo_toad", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["ntr_olgierd", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["mo_poroniec", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["mo_nekker", 1],
            ["mo_nekker_1", 1],
            ["mo_nekker_2", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Monster Deck 2",
        "description": "TBD",
        "leader": "mo_eredin_bronze",
        "faction": "monsters",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 1],
            ["spe_scorch", 3],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["mo_kayran", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["mo_arachas_behemoth", 1],
            ["mo_witch_velen", 1],
            ["mo_witch_velen_1", 1],
            ["mo_witch_velen_2", 1],
            ["ntr_olgierd", 1],
            ["mo_katakan", 1],
            ["mo_arachas", 1],
            ["mo_arachas_1", 1],
            ["mo_arachas_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["mo_bruxa", 1],
            ["mo_ekkima", 1],
            ["mo_fleder", 1],
            ["mo_garkain", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Scoia'Tael Deck 1",
        "description": "TBD",
        "leader": "sc_francesca_copper",
        "faction": "scoiatael",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sc_isengrim", 1],
            ["sc_milva", 1],
            ["sc_schirru", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sc_dol_infantry", 1],
            ["ntr_olgierd", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["sc_ciaran", 1],
            ["sc_dwarf", 1],
            ["sc_dwarf_1", 1],
            ["sc_dwarf_2", 1],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Scoia'Tael Deck 2",
        "description": "TBD",
        "leader": "sc_francesca_hope_of_the_aen_seidhe",
        "faction": "scoiatael",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 3],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_clear", 1],
            ["spe_fog", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sc_isengrim", 1],
            ["sc_milva", 1],
            ["sc_schirru", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sc_dol_infantry", 1],
            ["sc_dol_infantry_1", 1],
            ["sc_dol_infantry_2", 1],
            ["sc_filavandrel", 1],
            ["ntr_olgierd", 1],
            ["sc_havekar_support", 1],
            ["sc_havekar_support_1", 1],
            ["sc_havekar_support_2", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["ntr_dandelion", 1],
            ["ntr_gaunter_odimm", 1],
            ["ntr_cow", 1],
            ["sc_havekar_nurse", 1],
            ["sc_havekar_nurse_1", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Skellige Deck 1",
        "description": "TBD",
        "leader": "sk_crach_an_craite",
        "faction": "skellige",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_mardroeme", 1],
            ["spe_scorch", 1],
            ["spe_frost", 1],
            ["spe_storm", 1],
            ["spe_rain", 1],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sk_olaf", 1],
            ["sk_cerys", 1],
            ["sk_ermion", 1],
            ["ntr_villen", 1],
            ["ntr_yennefer", 1],
            ["sk_craite_warrior_1", 1],
            ["sk_craite_warrior_2", 1],
            ["sk_craite_warrior_3", 1],
            ["sk_dimun_pirate", 1],
            ["ntr_olgierd", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["sk_light_longship", 3],
            ["sk_birna", 1],
            ["ntr_dandelion", 1],
            ["sk_young_berserker", 3],
            ["sk_kambi", 1],
            ["ntr_mysterious_elf", 1]
        ]
    },
    {
        "title": "Default Skellige Deck 2",
        "description": "TBD",
        "leader": "sk_crach_an_craite",
        "faction": "skellige",
        "init_cards": [
            ["spe_horn", 1],
            ["spe_decoy", 2],
            ["ntr_ciri", 1],
            ["ntr_geralt", 1],
            ["sk_olaf", 1],
            ["sk_cerys", 1],
            ["ntr_villen", 1],
            ["sk_craite_warrior_1", 1],
            ["sk_craite_warrior_2", 1],
            ["sk_craite_warrior_3", 1],
            ["sk_dimun_pirate", 1],
            ["ntr_olgierd", 1],
            ["sk_war_longship_1", 1],
            ["sk_war_longship_2", 1],
            ["sk_shield_maiden_1", 1],
            ["sk_shield_maiden_2", 1],
            ["sk_shield_maiden_3", 1],
            ["ntr_gaunter_odimm_darkness", 3],
            ["sk_light_longship", 3],
            ["sk_birna", 1],
            ["ntr_mysterious_elf", 1]
        ]
    }
];
